// <auto-generated/> Emitted from the approved design source; see
// C:\Dev\MaxVsTheWorlds-Images\max-gen-mesh.html for the render these numbers produce.
// Do not hand-edit: change the design and re-emit.
using System.Collections.Generic;
using UnityEngine;

namespace MaxWorlds.VFX
{
    /// <summary>Max's materials. He runs the same warm/cool logic as the robots — cool jacket, warm
    /// hood and scarf — which is what makes him belong in the world rather than sit on top of it.
    /// His gadget glow is the only COOL light in the whole cast, against every robot's warm eye.</summary>
    public readonly struct MaxPalette
    {
        public readonly Material Skin, Hair, Jacket, Hood, Fabric, Dark, Boot, Sole, Metal, Eye, Goggle;

        /// <summary>MV-669 approved geometry: the utility belt band and its pouches. The only two new
        /// slots the new body adds — everything else (glove, goggle strap/frame, goggle lens) maps
        /// onto a material that already existed.</summary>
        public readonly Material Belt, Pouch;

        public MaxPalette(Material skin, Material hair, Material jacket, Material hood, Material fabric,
                          Material dark, Material boot, Material sole, Material metal, Material eye,
                          Material goggle, Material belt, Material pouch)
        {
            Skin = skin; Hair = hair; Jacket = jacket; Hood = hood; Fabric = fabric;
            Dark = dark; Boot = boot; Sole = sole; Metal = metal; Eye = eye; Goggle = goggle;
            Belt = belt; Pouch = pouch;
        }
    }

    /// <summary>What a built body hands back: the gadget glow the rig tints, and the hip pivots the run
    /// cycle drives (MV-474) — the same Eyes/Wheels split <see cref="RobotBodies.Body"/> already uses,
    /// so a director never has to hunt geometry down by name.
    ///
    /// MV-702 adds the LPPE/Shoulder Rack integration points: <see cref="RcdaGadget"/>/
    /// <see cref="LppeGadget"/> are the two gadget submeshes <c>MaxRig</c> toggles on
    /// <c>WeaponSystemState.ActivePrimary</c> (both built once, never rebuilt — a SetActive flip is
    /// cheaper than tearing down and re-emitting the fused body mesh on every primary swap), and
    /// <see cref="RackMount"/>/<see cref="RackTubeGlow"/> are the Shoulder Rack's mount, migrated here
    /// from its old placeholder home directly on <c>ShoulderRack</c> (see that class's history).</summary>
    public readonly struct MaxBodyResult
    {
        public readonly MeshRenderer[] GadgetGlow;
        public readonly Transform[] Hips;

        /// <summary>The RCDA's own gadget submesh — active by default (the RCDA is Max's run-start
        /// primary).</summary>
        public readonly GameObject RcdaGadget;

        /// <summary>The LPPE's gadget submesh — inactive by default, shown once
        /// <c>WeaponSystemState.ActivePrimary</c> reads <c>Lppe</c> (MV-689's World 2 morph).</summary>
        public readonly GameObject LppeGadget;

        /// <summary>The LPPE's own cyan-white lens — tinted separately from the RCDA's water-cyan tank
        /// glow so the two weapons don't share a light colour.</summary>
        public readonly MeshRenderer[] LppeGlow;

        /// <summary>The Shoulder Rack's 3-tube mount — inactive by default (unbought), shown once
        /// <c>ShoulderRack.IsBought</c> is true.</summary>
        public readonly GameObject RackMount;

        /// <summary>The three tube-tip lenses, tinted by <c>MaxRig</c> from dim (just fired) to bright
        /// (fully reloaded) as the rack reloads.</summary>
        public readonly MeshRenderer[] RackTubeGlow;

        /// <summary>MV-717: the moving parts MV-451's fused mesh dropped. All five (six, counting
        /// <see cref="Head"/>) are children of whatever <c>root</c> was built under, and <c>MaxRig</c>
        /// re-parents each one under its own torso pivot — see that class's <c>Build</c> for why.
        ///
        /// <see cref="Gun"/> wraps the whole gadget assembly (both submeshes and both hand grips) at
        /// its rest pose, so <c>TickGadget</c> can move and rotate one transform and carry everything
        /// welded to it along for free. <see cref="ArmL"/>/<see cref="ArmR"/> are the sleeve meshes
        /// <c>PoseArm</c> stretches every frame — a single tapered beam each, not the old static
        /// sleeve-plus-forearm pair, because a stretch target needs one transform to own the position,
        /// rotation AND scale it is given. <see cref="HandL"/>/<see cref="HandR"/> are the grip points
        /// <c>PoseArm</c> reaches for, parented under <see cref="Gun"/> so the hands cannot come off it.
        /// <see cref="Head"/> wraps the skull/hair/goggle geometry so <c>MaxRig</c> can yaw it
        /// independently for the head-lag cue.</summary>
        public readonly Transform Gun, ArmL, ArmR, HandL, HandR, Head;

        public MaxBodyResult(MeshRenderer[] gadgetGlow, Transform[] hips, GameObject rcdaGadget,
                             GameObject lppeGadget, MeshRenderer[] lppeGlow, GameObject rackMount,
                             MeshRenderer[] rackTubeGlow, Transform gun, Transform armL, Transform armR,
                             Transform handL, Transform handR, Transform head)
        {
            GadgetGlow = gadgetGlow;
            Hips = hips;
            RcdaGadget = rcdaGadget;
            LppeGadget = lppeGadget;
            LppeGlow = lppeGlow;
            RackMount = rackMount;
            RackTubeGlow = rackTubeGlow;
            Gun = gun;
            ArmL = armL;
            ArmR = armR;
            HandL = handL;
            HandR = handR;
            Head = head;
        }
    }

    /// <summary>
    /// Max's body, in metres, feet at y = 0 and +Z where he faces. MV-669: 32 approved parts (down
    /// from 60), authored feet-at-zero — see <c>MV-669-MaxBody-block.cs</c> in the design source
    /// folder, applied verbatim below except for two integration points the approved geometry
    /// deliberately leaves out:
    ///
    ///   * THE GADGET is not in the approved block. It is ported from the pre-MV-669 body and
    ///     re-seated against the new glove positions (see the gadget section below) — still off the
    ///     midline, still boxy with the tank on top, so it still reads as a tool and not a person.
    ///   * THE HIP PIVOTS are not in the block either — the leg parts are drawn at rest and reparented
    ///     under <see cref="Hip"/> exactly as before, so <c>TickRun</c>'s stride rotation (MV-474) has
    ///     something to swing.
    ///
    /// Revision 2 (2026-09-06), after Lee's playtest: the +10% root scale (<see
    /// cref="MaxRig.VisualScale"/>) is reverted to 1 — Lee tried the bigger Max and rejected it. The
    /// re-emitted block also shrinks the sneakers, thins and shortens the legs, and drops everything
    /// above the waist by 0.076 m to close the gap the shorter legs would otherwise open. The result
    /// measures within 2% of the original pre-MV-669 ~1.95 m crown (see the fix comment for the exact
    /// before/after numbers), so no compensating root scale was needed.
    /// </summary>
    public static class MaxBody
    {
        /// <summary>Build Max under <paramref name="root"/> (feet at y = 0 in <paramref name="root"/>'s
        /// space). <paramref name="hipY"/> is <c>MaxRig.HipY</c> — the waist height the two returned hip
        /// pivots sit at, so <c>TickRun</c>'s existing stride rotation (MV-474) has something to turn
        /// again. Returns the gadget glow and the hips so the rig can drive both.</summary>
        public static MaxBodyResult Build(Transform root, in MaxPalette p, float hipY)
        {
            var gadgetGlow = new List<MeshRenderer>(2);

            // MV-669 approved geometry doesn't include the legs (see the class doc) — they're drawn
            // at rest here and reparented under hip pivots exactly as before MV-669, so TickRun's
            // stride rotation (MV-474) still has a hinge to swing. Revision 2's re-emitted block moved
            // the sole/boot's authored x from 0.1421 to 0.132 (thinner legs), so the hip's own local x
            // moves with it — those two parts still carry a zero local x, matching the pre-MV-669
            // convention; every other leg part's local offset is its authored root-space position minus
            // the hip's, so at rest (identity hip rotation) it lands exactly where the approved block
            // puts it.
            var hipL = Hip(root, "HipL", new Vector3(-0.132f, hipY, 0f));
            var hipR = Hip(root, "HipR", new Vector3(0.132f, hipY, 0f));
            var hips = new[] { hipL, hipR };

            // ---- legs (MV-669-MaxBody-block.cs revision 2, items 1-8) ----------------------------
            Add(hipL, CharacterMeshes.Lathe(new[] { new Vector2(0f, 0f), new Vector2(0.124f, 0.014f), new Vector2(0.136f, 0.066f), new Vector2(0.124f, 0.1f), new Vector2(0f, 0.109f) }, 16), p.Sole, new Vector3(0f, 0f - hipY, 0.038f), Quaternion.identity, new Vector3(1f, 1f, 1.18f));
            Add(hipL, CharacterMeshes.Lathe(new[] { new Vector2(0f, 0.088f), new Vector2(0.116f, 0.104f), new Vector2(0.12f, 0.172f), new Vector2(0.096f, 0.21f), new Vector2(0f, 0.215f) }, 16), p.Boot, new Vector3(0f, 0f - hipY, 0.016f), Quaternion.identity, new Vector3(1f, 1f, 1.08f));
            Add(hipR, CharacterMeshes.Lathe(new[] { new Vector2(0f, 0f), new Vector2(0.124f, 0.014f), new Vector2(0.136f, 0.066f), new Vector2(0.124f, 0.1f), new Vector2(0f, 0.109f) }, 16), p.Sole, new Vector3(0f, 0f - hipY, 0.038f), Quaternion.identity, new Vector3(1f, 1f, 1.18f));
            Add(hipR, CharacterMeshes.Lathe(new[] { new Vector2(0f, 0.088f), new Vector2(0.116f, 0.104f), new Vector2(0.12f, 0.172f), new Vector2(0.096f, 0.21f), new Vector2(0f, 0.215f) }, 16), p.Boot, new Vector3(0f, 0f - hipY, 0.016f), Quaternion.identity, new Vector3(1f, 1f, 1.08f));
            Add(hipL, CharacterMeshes.Beam(0.58f, 0.126f, 0.108f, 7), p.Fabric, new Vector3(-0.132f + 0.132f, 0.482f - hipY, 0f), Quaternion.identity, Vector3.one);
            Add(hipL, CharacterMeshes.Prism(4, 0.052f, 0.046f, 0.14f, 0.24f, 0f), p.Fabric, new Vector3(-0.205f + 0.132f, 0.455f - hipY, 0.018f), Quaternion.identity, new Vector3(0.55f, 1f, 1.05f));
            Add(hipR, CharacterMeshes.Beam(0.58f, 0.126f, 0.108f, 7), p.Fabric, new Vector3(0.132f - 0.132f, 0.482f - hipY, 0f), Quaternion.identity, Vector3.one);
            Add(hipR, CharacterMeshes.Prism(4, 0.052f, 0.046f, 0.14f, 0.24f, 0f), p.Fabric, new Vector3(0.205f - 0.132f, 0.455f - hipY, 0.018f), Quaternion.identity, new Vector3(0.55f, 1f, 1.05f));

            // ---- belt, torso, hood (block items 9-14, verbatim) ----------------------------------
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0f, 0.784f), new Vector2(0.235f, 0.799f), new Vector2(0.245f, 0.879f), new Vector2(0.225f, 0.909f), new Vector2(0f, 0.914f) }, 20), p.Belt, new Vector3(0f, 0f, 0f), Quaternion.identity, Vector3.one);
            Add(root, CharacterMeshes.Prism(4, 0.058f, 0.052f, 0.115f, 0.22f, 0f), p.Pouch, new Vector3(-0.16f, 0.839f, 0.16f), Quaternion.identity, new Vector3(1f, 1f, 0.75f));
            Add(root, CharacterMeshes.Prism(4, 0.058f, 0.052f, 0.115f, 0.22f, 0f), p.Pouch, new Vector3(0.1f, 0.839f, 0.2f), Quaternion.identity, new Vector3(1.25f, 1f, 0.75f));
            Add(root, CharacterMeshes.Prism(4, 0.058f, 0.052f, 0.115f, 0.22f, 0f), p.Pouch, new Vector3(0.235f, 0.839f, -0.02f), Quaternion.identity, new Vector3(0.9f, 1f, 0.75f));
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0f, 0.874f), new Vector2(0.225f, 0.894f), new Vector2(0.215f, 1.024f), new Vector2(0.245f, 1.184f), new Vector2(0.275f, 1.324f), new Vector2(0.255f, 1.414f), new Vector2(0.17f, 1.464f), new Vector2(0f, 1.474f) }, 22), p.Jacket, new Vector3(0f, 0f, 0f), Quaternion.identity, Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0f, 1.224f), new Vector2(0.13f, 1.264f), new Vector2(0.15f, 1.364f), new Vector2(0.12f, 1.444f), new Vector2(0.045f, 1.484f), new Vector2(0f, 1.484f) }, 18), p.Hood, new Vector3(0f, 0f, -0.175f), Quaternion.identity, new Vector3(1.3f, 1f, 0.8f));

            // ---- MV-717: the old block's static sleeve+forearm+glove (6 parts, items 15-16 and their
            // mirror) are gone — PoseArm needs ONE transform per arm it can own position, rotation AND
            // scale on, so a two-piece static sleeve can't be reused as a stretch target. ArmL/ArmR
            // below (a single tapered beam each, HoodieShade like the old sleeve — see MaxRig's
            // HoodieShade doc for why) replace them; the glove becomes a small knuckle ball riding on
            // each hand grip instead (see the gadget section).

            // ---- head, hair, goggles (block items 17-32, verbatim) — wrapped in a "Head" pivot so ---
            // MaxRig can yaw it independently for the head-lag cue (MV-717). The pivot sits at root's
            // own origin (identity local transform), so every child keeps the exact authored offset
            // below; a pure yaw of the pivot only ever moves X/Z, and every child's X/Z is already
            // relative to the midline (x=0), so the pivot's own height is irrelevant to the result.
            var headGroup = new GameObject("Head");
            headGroup.transform.SetParent(root, worldPositionStays: false);
            var head = headGroup.transform;
            Add(head, CharacterMeshes.Lathe(new[] { new Vector2(0f, 1.474f), new Vector2(0.145f, 1.504f), new Vector2(0.195f, 1.584f), new Vector2(0.205f, 1.704f), new Vector2(0.185f, 1.794f), new Vector2(0f, 1.824f) }, 20), p.Skin, new Vector3(0f, 0f, 0f), Quaternion.identity, Vector3.one);
            Add(head, CharacterMeshes.Sphere(14), p.Eye, new Vector3(-0.085f, 1.659f, 0.175f), Quaternion.identity, new Vector3(0.062f, 0.07f, 0.045f));
            Add(head, CharacterMeshes.Sphere(14), p.Eye, new Vector3(0.085f, 1.659f, 0.175f), Quaternion.identity, new Vector3(0.062f, 0.07f, 0.045f));
            Add(head, CharacterMeshes.Lathe(new[] { new Vector2(0f, 1.724f), new Vector2(0.15f, 1.732f), new Vector2(0.222f, 1.76f), new Vector2(0.238f, 1.812f), new Vector2(0.232f, 1.868f), new Vector2(0.214f, 1.896f), new Vector2(0.15f, 1.908f), new Vector2(0f, 1.91f) }, 22), p.Hair, new Vector3(0f, 0f, -0.02f), Quaternion.identity, Vector3.one);
            Add(head, CharacterMeshes.Sphere(12), p.Hair, new Vector3(-0.108f, 1.912f, -0.19f), Quaternion.identity, new Vector3(0.17f, 0.135f, 0.16f));
            Add(head, CharacterMeshes.Sphere(12), p.Hair, new Vector3(0.118f, 1.889f, -0.205f), Quaternion.identity, new Vector3(0.152f, 0.122f, 0.148f));
            Add(head, CharacterMeshes.Lathe(new[] { new Vector2(0f, 1.796f), new Vector2(0.243f, 1.808f), new Vector2(0.248f, 1.858f), new Vector2(0.238f, 1.872f), new Vector2(0f, 1.876f) }, 24), p.Dark, new Vector3(0f, 0f, -0.022f), Quaternion.identity, Vector3.one);
            Add(head, CharacterMeshes.Lathe(new[] { new Vector2(0f, -0.028f), new Vector2(0.088f, -0.022f), new Vector2(0.093f, 0.026f), new Vector2(0.083f, 0.04f), new Vector2(0.069f, 0.042f), new Vector2(0.069f, 0.028f), new Vector2(0f, 0.024f) }, 18), p.Dark, new Vector3(-0.092f, 1.912f, 0.112f), Quaternion.Euler(24f, 0f, 0f), Vector3.one);
            Add(head, CharacterMeshes.Lathe(new[] { new Vector2(0f, 0.026f), new Vector2(0.068f, 0.03f), new Vector2(0.07f, 0.037f), new Vector2(0f, 0.039f) }, 18), p.Goggle, new Vector3(-0.092f, 1.912f, 0.112f), Quaternion.Euler(24f, 0f, 0f), Vector3.one);
            Add(head, CharacterMeshes.Lathe(new[] { new Vector2(0f, -0.028f), new Vector2(0.088f, -0.022f), new Vector2(0.093f, 0.026f), new Vector2(0.083f, 0.04f), new Vector2(0.069f, 0.042f), new Vector2(0.069f, 0.028f), new Vector2(0f, 0.024f) }, 18), p.Dark, new Vector3(0.092f, 1.912f, 0.112f), Quaternion.Euler(24f, 0f, 0f), Vector3.one);
            Add(head, CharacterMeshes.Lathe(new[] { new Vector2(0f, 0.026f), new Vector2(0.068f, 0.03f), new Vector2(0.07f, 0.037f), new Vector2(0f, 0.039f) }, 18), p.Goggle, new Vector3(0.092f, 1.912f, 0.112f), Quaternion.Euler(24f, 0f, 0f), Vector3.one);
            Add(head, CharacterMeshes.Prism(4, 0.026f, 0.026f, 0.1f, 0.1f, 0f), p.Dark, new Vector3(0f, 1.902f, 0.112f), Quaternion.Euler(24f, 0f, 90f), new Vector3(1f, 1f, 0.6f));

            // ---- MV-717: the sleeves. One tapered beam per arm, built at unit length (Beam's own
            // profile already centres on its own origin — see CharacterMeshes' doc) so PoseArm can
            // scale it directly to whatever length the shoulder-to-hand distance turns out to be, the
            // same trick the run cycle already uses for nothing else on this body because nothing else
            // needs to change length every frame. Parented under root for now; MaxRig re-parents each
            // one under the torso, which is the space PoseArm's own math already assumes (see its doc).
            // Given a resting-arm position/scale here rather than Vector3.zero/one: PoseArm overwrites
            // all three every frame once the rig is ticking, but a test that builds the body WITHOUT a
            // ticking rig (MV669MaxHeroPassTests' bounds checks) reads whatever is here at rest, and a
            // unit beam at the origin would render half a metre through the lawn.
            var armL = Add(root, CharacterMeshes.Beam(1f, 0.5f, 0.4f, 6), p.Hood, new Vector3(-0.29f, 1.0f, 0.03f), Quaternion.identity, new Vector3(0.16f, 0.45f, 0.16f));
            var armR = Add(root, CharacterMeshes.Beam(1f, 0.5f, 0.4f, 6), p.Hood, new Vector3(0.29f, 1.0f, 0.03f), Quaternion.identity, new Vector3(0.16f, 0.45f, 0.16f));

            // ---- the RCDA gadget (not in the approved block — ported from the pre-MV-669 body) -----
            //
            // Revision 2's re-emitted block moved the right glove to (0.325, 0.769, 0.03) — the block's
            // header states this explicitly. That is a further (+0.0171, -0.0315, +0.0016) from
            // revision 1's glove (0.3079, 0.8005, 0.0284), which the gadget below was already re-seated
            // to (MV-669's first approved-geometry commit). This section is that same revision-1
            // geometry translated once more by that delta so it stays welded to the new glove; rotations
            // and scales are still untouched. Combined with the revision-1 shift, the gadget has now
            // moved a total of (+0.0665, -0.2835, -0.04) from the true pre-MV-669 hand (0.2585, 1.0525,
            // 0.07) — down to hip height, matching the GDD's "holds the gadget two-handed at the hip".
            //
            // MV-702: parented under its own container so MaxRig can SetActive it off once the LPPE
            // morph (MV-689) flips WeaponSystemState.ActivePrimary — both gadgets are built once, at
            // Awake, and swapped by visibility rather than torn down and re-emitted.
            //
            // MV-717: that container is itself wrapped in "Gun" — sitting at root's own origin
            // (identity local transform), so every child below keeps the exact authored offset it
            // always had. MaxRig re-parents Gun onto a pivot placed at GunHipPos/GunHipRot (both
            // already expressed in the same torso space this whole gadget was designed for) using
            // worldPositionStays — Unity solves the "what local offset keeps this rendering exactly
            // where it already is" arithmetic, so nothing here has to.
            var gunAssembly = new GameObject("Gun");
            gunAssembly.transform.SetParent(root, worldPositionStays: false);
            var rcdaRoot = new GameObject("GadgetRcda");
            rcdaRoot.transform.SetParent(gunAssembly.transform, worldPositionStays: false);
            Add(rcdaRoot.transform, CharacterMeshes.Prism(4, 0.055f, 0.05f, 0.3f, 0.12f, 0f), p.Metal, new Vector3(0.2715f, 0.7565f, 0.11f), Quaternion.Euler(82f, -15f, 0f), Vector3.one);
            Add(rcdaRoot.transform, CharacterMeshes.Prism(4, 0.042f, 0.038f, 0.1f, 0.2f, 0f), p.Dark, new Vector3(0.2715f, 0.7515f, 0.3f), Quaternion.Euler(82f, -15f, 0f), Vector3.one);
            Add(rcdaRoot.transform, CharacterMeshes.Prism(6, 0.03f, 0.026f, 0.06f, 0.25f, 0f), p.Metal, new Vector3(0.2715f, 0.7485f, 0.365f), Quaternion.Euler(82f, -15f, 0f), Vector3.one);
            gadgetGlow.Add(Lens(rcdaRoot.transform, CharacterMeshes.Lathe(new[] { new Vector2(0.068f, 0f), new Vector2(0.082f, 0.035f), new Vector2(0.082f, 0.15f), new Vector2(0.064f, 0.19f) }, 16), new Vector3(0.2665f, 0.8415f, 0.05f), Quaternion.Euler(78f, -15f, 0f), Vector3.one));
            Add(rcdaRoot.transform, CharacterMeshes.Lathe(new[] { new Vector2(0.04f, 0f), new Vector2(0.046f, 0.015f), new Vector2(0.038f, 0.03f) }, 12), p.Dark, new Vector3(0.2665f, 0.8415f, 0.23f), Quaternion.Euler(78f, -15f, 0f), Vector3.one);
            Add(rcdaRoot.transform, CharacterMeshes.Prism(4, 0.04f, 0.034f, 0.13f, 0.2f, 0f), p.Dark, new Vector3(0.3095f, 0.6765f, 0f), Quaternion.Euler(22f, -15f, 0f), Vector3.one);
            Add(rcdaRoot.transform, CharacterMeshes.Prism(4, 0.034f, 0.03f, 0.08f, 0.22f, 0f), p.Dark, new Vector3(0.2495f, 0.7065f, 0.23f), Quaternion.Euler(26f, -15f, 0f), Vector3.one);
            Add(rcdaRoot.transform, CharacterMeshes.Prism(4, 0.048f, 0.044f, 0.035f, 0.15f, 0f), p.Boot, new Vector3(0.2715f, 0.7615f, 0.185f), Quaternion.Euler(82f, -15f, 0f), Vector3.one);
            gadgetGlow.Add(Lens(rcdaRoot.transform, CharacterMeshes.Sphere(14), new Vector3(0.2715f, 0.7465f, 0.405f), Quaternion.identity, new Vector3(0.055f, 0.055f, 0.038f)));

            // ---- the LPPE gadget (MV-702) — a laser-pointer-and-drill hybrid, welded to the same ----
            // glove position the RCDA occupies (a hidden gadget swap has to land in exactly the same
            // hands), reusing the RCDA's own grip/stock parts so the two weapons read as siblings from
            // the same toolbox rather than two unrelated props. Boxy Prism housing + a ridged Lathe
            // "coil" replace the RCDA's tank; a tapered hex Prism nose replaces its round barrel; one
            // cyan-white lens (the ticket's "cyan-white lens") stands in for the RCDA's two.
            var lppeGlow = new List<MeshRenderer>(1);
            var lppeRoot = new GameObject("GadgetLppe");
            lppeRoot.transform.SetParent(gunAssembly.transform, worldPositionStays: false);
            Add(lppeRoot.transform, CharacterMeshes.Prism(4, 0.06f, 0.05f, 0.32f, 0.1f, 0f), p.Metal, new Vector3(0.2715f, 0.7565f, 0.11f), Quaternion.Euler(82f, -15f, 0f), Vector3.one);
            Add(lppeRoot.transform, CharacterMeshes.Lathe(new[] { new Vector2(0.036f, 0f), new Vector2(0.05f, 0.018f), new Vector2(0.036f, 0.036f), new Vector2(0.05f, 0.054f), new Vector2(0.036f, 0.072f), new Vector2(0.05f, 0.09f), new Vector2(0.036f, 0.108f), new Vector2(0f, 0.118f) }, 14), p.Dark, new Vector3(0.2715f, 0.75f, 0.24f), Quaternion.Euler(82f, -15f, 0f), Vector3.one);
            Add(lppeRoot.transform, CharacterMeshes.Prism(6, 0.032f, 0.012f, 0.09f, 0.3f, 10f), p.Metal, new Vector3(0.2715f, 0.7485f, 0.365f), Quaternion.Euler(82f, -15f, 0f), Vector3.one);
            Add(lppeRoot.transform, CharacterMeshes.Prism(4, 0.04f, 0.034f, 0.13f, 0.2f, 0f), p.Dark, new Vector3(0.3095f, 0.6765f, 0f), Quaternion.Euler(22f, -15f, 0f), Vector3.one);
            Add(lppeRoot.transform, CharacterMeshes.Prism(4, 0.034f, 0.03f, 0.08f, 0.22f, 0f), p.Dark, new Vector3(0.2495f, 0.7065f, 0.23f), Quaternion.Euler(26f, -15f, 0f), Vector3.one);
            Add(lppeRoot.transform, CharacterMeshes.Prism(4, 0.048f, 0.044f, 0.035f, 0.15f, 0f), p.Boot, new Vector3(0.2715f, 0.7615f, 0.185f), Quaternion.Euler(82f, -15f, 0f), Vector3.one);
            lppeGlow.Add(Lens(lppeRoot.transform, CharacterMeshes.Sphere(14), new Vector3(0.2715f, 0.7465f, 0.405f), Quaternion.identity, new Vector3(0.05f, 0.05f, 0.036f)));
            lppeRoot.SetActive(false);   // RCDA is Max's run-start primary; MaxRig flips these on ActivePrimary

            // ---- MV-717: the two grip points, parented under the gun so the hands cannot come off it
            // no matter how it is posed. MV-730 (Lee: "his left arm comes right across his body to hold
            // the device... to fire the weapon his right hand should come up above waist height") swaps
            // which grip each hand takes: measured in the built rig at full aim, the coordinates near
            // the tank/nose resolve to world y ~0.87-1.0 (clear of the waist) while the ones near the
            // trigger/stock resolve to world y ~0.75-0.90 (barely above it) — an artefact of how far
            // each point sits from the shoulder-roll pivot, not something visible in these local numbers
            // alone. HandR now takes the tank/nose coordinates, so the RIGHT hand is the one that
            // visibly rises to drive the gadget; HandL takes the trigger/stock coordinates, so the LEFT
            // hand stays low and reads as bracing the gadget rather than crossing up to operate it. A
            // small dark knuckle ball on each stands in for the old static glove.
            var handR = new GameObject("HandR").transform;
            handR.SetParent(gunAssembly.transform, worldPositionStays: false);
            handR.localPosition = new Vector3(0.27f, 0.75f, 0.30f);
            Add(handR, CharacterMeshes.Sphere(10), p.Dark, Vector3.zero, Quaternion.identity, new Vector3(0.09f, 0.09f, 0.09f));

            var handL = new GameObject("HandL").transform;
            handL.SetParent(gunAssembly.transform, worldPositionStays: false);
            handL.localPosition = new Vector3(0.29f, 0.70f, 0.05f);
            Add(handL, CharacterMeshes.Sphere(10), p.Dark, Vector3.zero, Quaternion.identity, new Vector3(0.09f, 0.09f, 0.09f));

            // ---- the Shoulder Rack mount (MV-702) — migrated from ShoulderRack's own placeholder ----
            // GameObject (see that class's history) onto MaxRig proper, so it stops being tinted by
            // CharacterSkinDirector (which claims every renderer under Max's own IDamageable — see
            // MaxRig's class doc). Right shoulder, outboard of the arm beam at (0.275, 1.204, 0.01).
            var rackTubeGlow = new MeshRenderer[3];
            var rackRoot = new GameObject("ShoulderRackMount");
            rackRoot.transform.SetParent(root, worldPositionStays: false);
            Add(rackRoot.transform, CharacterMeshes.Prism(4, 0.09f, 0.08f, 0.3f, 0.08f, 0f), p.Metal, new Vector3(0.33f, 1.28f, 0.02f), Quaternion.Euler(0f, -15f, 0f), Vector3.one);
            for (int i = 0; i < 3; i++)
            {
                float yOff = (i - 1) * 0.075f;
                Add(rackRoot.transform, CharacterMeshes.Beam(0.22f, 0.032f, 0.028f, 8), p.Dark, new Vector3(0.33f, 1.28f + yOff, 0.16f), Quaternion.Euler(90f, -15f, 0f), Vector3.one);
                rackTubeGlow[i] = Lens(rackRoot.transform, CharacterMeshes.Lathe(new[] { new Vector2(0f, 0f), new Vector2(0.03f, 0.012f), new Vector2(0.024f, 0.03f) }, 10), new Vector3(0.33f, 1.28f + yOff, 0.275f), Quaternion.Euler(90f, -15f, 0f), Vector3.one);
            }
            rackRoot.SetActive(false);   // shown only once ShoulderRack.IsBought (AC2, carried over from MV-694)

            return new MaxBodyResult(gadgetGlow.ToArray(), hips, rcdaRoot, lppeRoot, lppeGlow.ToArray(),
                                     rackRoot, rackTubeGlow, gunAssembly.transform, armL, armR, handL, handR, head);
        }

        /// <summary>An empty rotation handle — the hinge <see cref="MaxRig.TickRun"/> swings a foot
        /// from, since nothing in the generated mesh is itself a joint.</summary>
        private static Transform Hip(Transform root, string name, Vector3 at)
        {
            var go = new GameObject(name);
            go.transform.SetParent(root, worldPositionStays: false);
            go.transform.localPosition = at;
            return go.transform;
        }

        private static Transform Add(Transform root, Mesh mesh, Material mat,
                                     Vector3 at, Quaternion rot, Vector3 scale)
            => CharacterPart.Add(root, mesh, mat, at, rot, scale);

        private static MeshRenderer Lens(Transform root, Mesh mesh,
                                         Vector3 at, Quaternion rot, Vector3 scale)
            => CharacterPart.AddLens(root, mesh, at, rot, scale);
    }
}
