// <auto-generated/> Emitted from the approved design source; see
// C:\Dev\MaxVsTheWorlds-Images\max-gen-mesh.html for the render these numbers produce.
// Do not hand-edit: change the design and re-emit.
using System.Collections.Generic;
using UnityEngine;

namespace MaxWorlds.VFX
{
    /// <summary>Max's materials. He runs the same warm/cool logic as the robots — cool jacket, warm
    /// hood and scarf — which is what makes him belong in the world rather than sit on top of it.
    /// His gadget glow is the only COOL light in the whole cast, against every robot's warm eye.</summary>
    public readonly struct MaxPalette
    {
        public readonly Material Skin, Hair, Jacket, Hood, Fabric, Dark, Boot, Sole, Metal, Eye, Goggle;

        public MaxPalette(Material skin, Material hair, Material jacket, Material hood, Material fabric,
                          Material dark, Material boot, Material sole, Material metal, Material eye,
                          Material goggle)
        {
            Skin = skin; Hair = hair; Jacket = jacket; Hood = hood; Fabric = fabric;
            Dark = dark; Boot = boot; Sole = sole; Metal = metal; Eye = eye; Goggle = goggle;
        }
    }

    /// <summary>What a built body hands back: the gadget glow the rig tints, and the hip pivots the run
    /// cycle drives (MV-474) — the same Eyes/Wheels split <see cref="RobotBodies.Body"/> already uses,
    /// so a director never has to hunt geometry down by name.</summary>
    public readonly struct MaxBodyResult
    {
        public readonly MeshRenderer[] GadgetGlow;
        public readonly Transform[] Hips;

        public MaxBodyResult(MeshRenderer[] gadgetGlow, Transform[] hips)
        {
            GadgetGlow = gadgetGlow;
            Hips = hips;
        }
    }

    /// <summary>
    /// Max's body, in metres, feet at y = 0 and +Z where he faces. ~1.95 m to the crown.
    ///
    /// Two things here are load-bearing and easy to break by "tidying":
    ///
    ///   * ELBOWS ARE EXPLICIT, not a shoulder-to-hand midpoint. With both hands on a blaster carried
    ///     to his right, a midpoint elbow lands inside the jacket lathe and the whole left upper arm
    ///     draws inside the torso — the arm reads as missing.
    ///   * THE BLASTER IS OFF THE MIDLINE, boxy, with the tank on top. A smooth tapered cylinder
    ///     projecting forward from the pelvis reads as something other than a water gun.
    /// </summary>
    public static class MaxBody
    {
        /// <summary>Build Max under <paramref name="root"/> (feet at y = 0 in <paramref name="root"/>'s
        /// space). <paramref name="hipY"/> is <c>MaxRig.HipY</c> — the waist height the two returned hip
        /// pivots sit at, so <c>TickRun</c>'s existing stride rotation (MV-474) has something to turn
        /// again. Returns the gadget glow and the hips so the rig can drive both.</summary>
        public static MaxBodyResult Build(Transform root, in MaxPalette p, float hipY)
        {
            var eyes = new List<MeshRenderer>(1);
            var wheels = new List<Transform>(0);   // Max walks; nothing on him rolls

            // The two feet hang off hip pivots at waist height (MV-474) instead of straight off `root`,
            // so TickRun's stride rotation has a hinge to swing them from — the same Eyes/Wheels-style
            // handback RobotBodies uses for its wheels, just a rotation pivot instead of a spin axle.
            // Local offsets below are each foot's ORIGINAL root-space position minus the hip's own
            // position, so at rest (identity hip rotation) every mesh lands exactly where it always did.
            var hipL = Hip(root, "HipL", new Vector3(-0.115f, hipY, 0f));
            var hipR = Hip(root, "HipR", new Vector3(0.115f, hipY, 0f));
            var hips = new[] { hipL, hipR };

            Add(hipL, CharacterMeshes.Lathe(new[] { new Vector2(0.105f, 0f), new Vector2(0.125f, 0.03f), new Vector2(0.115f, 0.055f) }, 12), p.Sole, new Vector3(0f, 0.015f - hipY, 0.035f), Quaternion.identity, Vector3.one);
            Add(hipL, CharacterMeshes.Prism(7, 0.108f, 0.082f, 0.13f, 0.3f, 0f), p.Boot, new Vector3(0f, 0.125f - hipY, 0.025f), Quaternion.Euler(6f, 0f, 0f), Vector3.one);
            Add(hipL, CharacterMeshes.Lathe(new[] { new Vector2(0.075f, 0f), new Vector2(0.088f, 0.02f), new Vector2(0.07f, 0.045f) }, 10), p.Boot, new Vector3(0f, 0.195f - hipY, 0.015f), Quaternion.identity, Vector3.one);
            Add(hipR, CharacterMeshes.Lathe(new[] { new Vector2(0.105f, 0f), new Vector2(0.125f, 0.03f), new Vector2(0.115f, 0.055f) }, 12), p.Sole, new Vector3(0f, 0.015f - hipY, 0.035f), Quaternion.identity, Vector3.one);
            Add(hipR, CharacterMeshes.Prism(7, 0.108f, 0.082f, 0.13f, 0.3f, 0f), p.Boot, new Vector3(0f, 0.125f - hipY, 0.025f), Quaternion.Euler(6f, 0f, 0f), Vector3.one);
            Add(hipR, CharacterMeshes.Lathe(new[] { new Vector2(0.075f, 0f), new Vector2(0.088f, 0.02f), new Vector2(0.07f, 0.045f) }, 10), p.Boot, new Vector3(0f, 0.195f - hipY, 0.015f), Quaternion.identity, Vector3.one);
            Add(root, CharacterMeshes.Beam(0.3003f, 0.052f, 0.062f, 7), p.Skin, new Vector3(-0.12f, 0.35f, 0.005f), Quaternion.Euler(2.699f, -135f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Sphere(12), p.Skin, new Vector3(-0.125f, 0.52f, 0f), Quaternion.identity, new Vector3(0.13f, 0.12f, 0.13f));
            Add(root, CharacterMeshes.Beam(0.3003f, 0.052f, 0.062f, 7), p.Skin, new Vector3(0.12f, 0.35f, 0.005f), Quaternion.Euler(2.699f, 135f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Sphere(12), p.Skin, new Vector3(0.125f, 0.52f, 0f), Quaternion.identity, new Vector3(0.13f, 0.12f, 0.13f));
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.2f, 0f), new Vector2(0.215f, 0.1f), new Vector2(0.2f, 0.22f), new Vector2(0.175f, 0.3f) }, 16), p.Fabric, new Vector3(0f, 0.5f, 0f), Quaternion.identity, Vector3.one);
            Add(root, CharacterMeshes.Prism(6, 0.055f, 0.048f, 0.16f, 0.22f, 0f), p.Fabric, new Vector3(-0.2f, 0.63f, 0.02f), Quaternion.Euler(0f, 0f, -6f), Vector3.one);
            Add(root, CharacterMeshes.Prism(6, 0.055f, 0.048f, 0.16f, 0.22f, 0f), p.Fabric, new Vector3(0.2f, 0.63f, 0.02f), Quaternion.Euler(0f, 0f, 6f), Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.175f, 0f), new Vector2(0.19f, 0.02f), new Vector2(0.175f, 0.045f) }, 18), p.Dark, new Vector3(0f, 0.8f, 0f), Quaternion.identity, Vector3.one);
            Add(root, CharacterMeshes.Prism(6, 0.075f, 0.0645f, 0.085f, 0.26f, 0f), p.Dark, new Vector3(0.1061f, 0.8f, 0.1515f), Quaternion.Euler(0f, 35f, 7f), Vector3.one);
            Add(root, CharacterMeshes.Prism(6, 0.06f, 0.0516f, 0.07f, 0.26f, 0f), p.Dark, new Vector3(0.0925f, 0.8f, -0.1602f), Quaternion.Euler(0f, 150f, -6f), Vector3.one);
            Add(root, CharacterMeshes.Prism(6, 0.085f, 0.0731f, 0.1f, 0.26f, 0f), p.Dark, new Vector3(-0.1061f, 0.8f, -0.1515f), Quaternion.Euler(0f, 215f, 7f), Vector3.one);
            Add(root, CharacterMeshes.Prism(6, 0.055f, 0.0473f, 0.065f, 0.26f, 0f), p.Dark, new Vector3(-0.1602f, 0.8f, 0.0925f), Quaternion.Euler(0f, 300f, -6f), Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.175f, 0f), new Vector2(0.205f, 0.1f), new Vector2(0.225f, 0.3f), new Vector2(0.235f, 0.44f), new Vector2(0.2f, 0.52f) }, 20), p.Jacket, new Vector3(0f, 0.84f, 0f), Quaternion.identity, Vector3.one);
            Add(root, CharacterMeshes.Sphere(14), p.Jacket, new Vector3(-0.2f, 1.32f, 0f), Quaternion.identity, new Vector3(0.155f, 0.145f, 0.175f));
            Add(root, CharacterMeshes.Sphere(14), p.Jacket, new Vector3(0.2f, 1.32f, 0f), Quaternion.identity, new Vector3(0.155f, 0.145f, 0.175f));
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.2f, 0f), new Vector2(0.235f, 0.08f), new Vector2(0.2f, 0.17f), new Vector2(0.13f, 0.22f) }, 18), p.Hood, new Vector3(0f, 1.28f, -0.1f), Quaternion.Euler(16f, 0f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.115f, 0f), new Vector2(0.135f, 0.035f), new Vector2(0.125f, 0.075f), new Vector2(0.1f, 0.1f) }, 16), p.Hood, new Vector3(0f, 1.34f, 0f), Quaternion.identity, Vector3.one);
            Add(root, CharacterMeshes.Beam(0.0707f, 0.055f, 0.062f, 7), p.Skin, new Vector3(0f, 1.435f, 0.005f), Quaternion.Euler(8.1301f, 0f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0f, 0f), new Vector2(0.112f, 0.048f), new Vector2(0.163f, 0.14f), new Vector2(0.17f, 0.235f), new Vector2(0.142f, 0.32f), new Vector2(0f, 0.368f) }, 22), p.Skin, new Vector3(0f, 1.45f, 0f), Quaternion.identity, Vector3.one);
            Add(root, CharacterMeshes.Sphere(10), p.Skin, new Vector3(-0.156f, 1.63f, -0.005f), Quaternion.identity, new Vector3(0.052f, 0.078f, 0.058f));
            Add(root, CharacterMeshes.Sphere(10), p.Skin, new Vector3(0.156f, 1.63f, -0.005f), Quaternion.identity, new Vector3(0.052f, 0.078f, 0.058f));
            Add(root, CharacterMeshes.Prism(4, 0.045f, 0.032f, 0.022f, 0.2f, 0f), p.Hair, new Vector3(-0.064f, 1.678f, 0.132f), Quaternion.Euler(90f, 0f, 15f), Vector3.one);
            Add(root, CharacterMeshes.Prism(4, 0.045f, 0.032f, 0.022f, 0.2f, 0f), p.Hair, new Vector3(0.064f, 1.678f, 0.132f), Quaternion.Euler(90f, 0f, -15f), Vector3.one);
            Add(root, CharacterMeshes.Sphere(12), p.Eye, new Vector3(-0.062f, 1.632f, 0.138f), Quaternion.identity, new Vector3(0.055f, 0.062f, 0.03f));
            Add(root, CharacterMeshes.Sphere(12), p.Eye, new Vector3(0.062f, 1.632f, 0.138f), Quaternion.identity, new Vector3(0.055f, 0.062f, 0.03f));
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.166f, 0f), new Vector2(0.176f, 0.018f), new Vector2(0.166f, 0.038f) }, 20), p.Dark, new Vector3(0f, 1.695f, -0.005f), Quaternion.Euler(8f, 0f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.052f, 0f), new Vector2(0.062f, 0.014f), new Vector2(0.05f, 0.03f) }, 14), p.Goggle, new Vector3(-0.072f, 1.706f, 0.128f), Quaternion.Euler(72f, 0f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.052f, 0f), new Vector2(0.062f, 0.014f), new Vector2(0.05f, 0.03f) }, 14), p.Goggle, new Vector3(0.072f, 1.706f, 0.128f), Quaternion.Euler(72f, 0f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.162f, 0f), new Vector2(0.1908f, 0.07f), new Vector2(0.18f, 0.16f), new Vector2(0.1224f, 0.24f) }, 20), p.Hair, new Vector3(0f, 1.695f, -0.01f), Quaternion.identity, Vector3.one);
            Add(root, CharacterMeshes.Beam(0.24f, 0.078f, 0.0234f, 5), p.Hair, new Vector3(0.0402f, 1.8586f, 0.2279f), Quaternion.Euler(58f, 10f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Beam(0.19f, 0.066f, 0.0198f, 5), p.Hair, new Vector3(0.1627f, 1.8275f, 0.1465f), Quaternion.Euler(70f, 48f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Beam(0.22f, 0.074f, 0.0222f, 5), p.Hair, new Vector3(0.2185f, 1.8597f, -0.0076f), Quaternion.Euler(54f, 92f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Beam(0.16f, 0.058f, 0.0174f, 5), p.Hair, new Vector3(0.1491f, 1.8144f, -0.1439f), Quaternion.Euler(76f, 134f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Beam(0.26f, 0.084f, 0.0252f, 5), p.Hair, new Vector3(0.0079f, 1.882f, -0.2261f), Quaternion.Euler(48f, 178f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Beam(0.17f, 0.06f, 0.018f, 5), p.Hair, new Vector3(-0.1177f, 1.8213f, -0.1745f), Quaternion.Euler(72f, -146f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Beam(0.21f, 0.072f, 0.0216f, 5), p.Hair, new Vector3(-0.2102f, 1.8537f, -0.0524f), Quaternion.Euler(56f, -104f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Beam(0.15f, 0.054f, 0.0162f, 5), p.Hair, new Vector3(-0.1796f, 1.808f, 0.0955f), Quaternion.Euler(80f, -62f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Beam(0.2f, 0.068f, 0.0204f, 5), p.Hair, new Vector3(-0.1089f, 1.8419f, 0.1887f), Quaternion.Euler(62f, -30f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Beam(0.17f, 0.064f, 0.0192f, 5), p.Hair, new Vector3(0.0731f, 1.8714f, 0.15f), Quaternion.Euler(26f, 26f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Beam(0.18f, 0.066f, 0.0198f, 5), p.Hair, new Vector3(-0.0559f, 1.8784f, -0.1535f), Quaternion.Euler(22f, -160f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Beam(0.15f, 0.058f, 0.0174f, 5), p.Hair, new Vector3(-0.1671f, 1.86f, 0f), Quaternion.Euler(30f, -90f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Beam(0.2554f, 0.068f, 0.054f, 7), p.Jacket, new Vector3(-0.1975f, 1.215f, 0.095f), Quaternion.Euler(131.7317f, 4.514f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Sphere(12), p.Jacket, new Vector3(-0.19f, 1.13f, 0.19f), Quaternion.identity, new Vector3(0.105f, 0.1f, 0.105f));
            Add(root, CharacterMeshes.Beam(0.3727f, 0.05f, 0.042f, 7), p.Skin, new Vector3(-0.02f, 1.09f, 0.255f), Quaternion.Euler(102.3952f, 69.0755f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Prism(6, 0.055f, 0.05f, 0.09f, 0.28f, 0f), p.Dark, new Vector3(0.15f, 1.05f, 0.32f), Quaternion.Euler(70f, 0f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Beam(0.2118f, 0.068f, 0.054f, 7), p.Jacket, new Vector3(0.2335f, 1.2025f, 0.03f), Quaternion.Euler(157.0035f, 43.5312f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Sphere(12), p.Jacket, new Vector3(0.262f, 1.105f, 0.06f), Quaternion.identity, new Vector3(0.105f, 0.1f, 0.105f));
            Add(root, CharacterMeshes.Beam(0.1071f, 0.05f, 0.042f, 7), p.Skin, new Vector3(0.2585f, 1.0525f, 0.07f), Quaternion.Euler(168.5906f, -19.29f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Prism(6, 0.055f, 0.05f, 0.09f, 0.28f, 0f), p.Dark, new Vector3(0.255f, 1f, 0.08f), Quaternion.Euler(70f, 0f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Prism(4, 0.055f, 0.05f, 0.3f, 0.12f, 0f), p.Metal, new Vector3(0.205f, 1.04f, 0.15f), Quaternion.Euler(82f, -15f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Prism(4, 0.042f, 0.038f, 0.1f, 0.2f, 0f), p.Dark, new Vector3(0.205f, 1.035f, 0.34f), Quaternion.Euler(82f, -15f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Prism(6, 0.03f, 0.026f, 0.06f, 0.25f, 0f), p.Metal, new Vector3(0.205f, 1.032f, 0.405f), Quaternion.Euler(82f, -15f, 0f), Vector3.one);
            eyes.Add(Lens(root, CharacterMeshes.Lathe(new[] { new Vector2(0.068f, 0f), new Vector2(0.082f, 0.035f), new Vector2(0.082f, 0.15f), new Vector2(0.064f, 0.19f) }, 16), new Vector3(0.2f, 1.125f, 0.09f), Quaternion.Euler(78f, -15f, 0f), Vector3.one));
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.04f, 0f), new Vector2(0.046f, 0.015f), new Vector2(0.038f, 0.03f) }, 12), p.Dark, new Vector3(0.2f, 1.125f, 0.27f), Quaternion.Euler(78f, -15f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Prism(4, 0.04f, 0.034f, 0.13f, 0.2f, 0f), p.Dark, new Vector3(0.243f, 0.96f, 0.04f), Quaternion.Euler(22f, -15f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Prism(4, 0.034f, 0.03f, 0.08f, 0.22f, 0f), p.Dark, new Vector3(0.183f, 0.99f, 0.27f), Quaternion.Euler(26f, -15f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Prism(4, 0.048f, 0.044f, 0.035f, 0.15f, 0f), p.Boot, new Vector3(0.205f, 1.045f, 0.225f), Quaternion.Euler(82f, -15f, 0f), Vector3.one);
            eyes.Add(Lens(root, CharacterMeshes.Sphere(14), new Vector3(0.205f, 1.03f, 0.445f), Quaternion.identity, new Vector3(0.055f, 0.055f, 0.038f)));
            Add(root, CharacterMeshes.Prism(6, 0.155f, 0.135f, 0.3f, 0.26f, 0f), p.Fabric, new Vector3(0f, 1.14f, -0.2f), Quaternion.Euler(-8f, 0f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.05f, 0f), new Vector2(0.06f, 0.02f), new Vector2(0.048f, 0.05f) }, 10), p.Dark, new Vector3(0.09f, 1.24f, -0.3f), Quaternion.Euler(80f, 0f, 0f), Vector3.one);
            return new MaxBodyResult(eyes.ToArray(), hips);
        }

        /// <summary>An empty rotation handle — the hinge <see cref="MaxRig.TickRun"/> swings a foot
        /// from, since nothing in the generated mesh is itself a joint.</summary>
        private static Transform Hip(Transform root, string name, Vector3 at)
        {
            var go = new GameObject(name);
            go.transform.SetParent(root, worldPositionStays: false);
            go.transform.localPosition = at;
            return go.transform;
        }

        private static Transform Add(Transform root, Mesh mesh, Material mat,
                                     Vector3 at, Quaternion rot, Vector3 scale)
            => CharacterPart.Add(root, mesh, mat, at, rot, scale);

        private static MeshRenderer Lens(Transform root, Mesh mesh,
                                         Vector3 at, Quaternion rot, Vector3 scale)
            => CharacterPart.AddLens(root, mesh, at, rot, scale);
    }
}
