// <auto-generated/> Emitted from the approved design source; see
// C:\Dev\MaxVsTheWorlds-Images\robot-gen-mesh.html for the render these numbers produce.
// Do not hand-edit: change the design and re-emit, or the render and the game diverge.
using System.Collections.Generic;
using UnityEngine;
using MaxWorlds.Enemies;

namespace MaxWorlds.VFX
{
    /// <summary>The four materials every Backyard robot is built from. Three are SHARED across the
    /// whole roster — which is what makes seven kinds read as one family assembled from one shed —
    /// and only <see cref="Warm"/> varies, because it is the one carrying gameplay information.</summary>
    public readonly struct RobotPalette
    {
        /// <summary>The kind's own hue, straight from CharacterSkin. The gameplay colour code.</summary>
        public readonly Material Warm;
        /// <summary>Shared cool. Identical on every kind.</summary>
        public readonly Material Cool;
        /// <summary>Shared near-black: every joint, leg, claw, cable and eye bezel.</summary>
        public readonly Material Dark;
        /// <summary>The single Tier-1 gold tell. It foreshadows the Curator and only pays if withheld.</summary>
        public readonly Material Gold;

        public RobotPalette(Material warm, Material cool, Material dark, Material gold)
        {
            Warm = warm; Cool = cool; Dark = dark; Gold = gold;
        }
    }

    /// <summary>
    /// Every Backyard robot's visible body, in metres, feet at y = 0 and +Z where it is running.
    ///
    /// Built from <see cref="CharacterMeshes"/>, not primitives — see that class for why. Two
    /// consequences worth knowing: the geometry is shared across every instance of a kind, so a
    /// swarm costs what one robot costs; and SIZE IS REAL here, because
    /// <c>ParentScale.MakeMetreSpace</c> cancels the archetype's body scale before any of this is
    /// placed. That cancellation is why Rusher, Heavy and Brute used to be the same size on screen
    /// despite three different <c>BodyScale</c> values.
    /// </summary>
    public static class RobotBodies
    {
        /// <summary>Build <paramref name="kind"/>'s body under <paramref name="root"/> and return the
        /// emissive lenses the rig drives as its tell.</summary>
        public static Body Build(EnemyKind kind, Transform root, in RobotPalette p)
        {
            var eyes = new List<MeshRenderer>(2);
            var wheels = new List<Transform>(6);
            switch (kind)
            {
                case EnemyKind.Launcher: BuildLauncher(root, p, eyes, wheels); break;
                case EnemyKind.Blinker:  BuildBlinker(root, p, eyes, wheels); break;
                case EnemyKind.Gunner:   BuildGunner(root, p, eyes, wheels); break;
                case EnemyKind.Bruiser:  BuildBruiser(root, p, eyes, wheels); break;
                case EnemyKind.Heavy:    BuildHeavy(root, p, eyes, wheels); break;
                case EnemyKind.Brute:    BuildBrute(root, p, eyes, wheels); break;
                default:                 BuildRusher(root, p, eyes, wheels); break;
            }
            return new Body(eyes.ToArray(), wheels.ToArray());
        }

        /// <summary>What a built body hands back: the lenses the eye tell drives, and the wheels the
        /// rig spins. Wheels are returned rather than found by name because a name search is a
        /// silent-failure mode — rename a part and the robot stops rolling with no error.</summary>
        public readonly struct Body
        {
            public readonly MeshRenderer[] Eyes;
            /// <summary>Every rolling part, already oriented so its LOCAL Y is the axle. Spin with
            /// <c>Rotate(Vector3.up, degrees, Space.Self)</c>.</summary>
            public readonly Transform[] Wheels;

            public Body(MeshRenderer[] eyes, Transform[] wheels) { Eyes = eyes; Wheels = wheels; }
        }

        /// <summary>Rusher — a low buggy on two outboard drive wheels with a front castor. Raked forward, body slung between the wheels. Rolls, because nothing animates a leg.</summary>
        private static void BuildRusher(Transform root, in RobotPalette p,
                                    List<MeshRenderer> eyes, List<Transform> wheels)
        {
            wheels.Add(Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.0705f, -0.0675f), new Vector2(0.2021f, -0.0675f), new Vector2(0.235f, -0.0405f), new Vector2(0.235f, 0.0405f), new Vector2(0.2021f, 0.0675f), new Vector2(0.0705f, 0.0675f) }, 22), p.Dark, new Vector3(0f, 0.235f, -0.02f), Quaternion.Euler(0f, 0f, 90f), Vector3.one));
            wheels.Add(Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.1222f, -0.0243f), new Vector2(0.141f, 0f), new Vector2(0.1222f, 0.0243f) }, 16), p.Warm, new Vector3(0f, 0.235f, -0.02f), Quaternion.Euler(0f, 0f, 90f), Vector3.one));
            Add(root, CharacterMeshes.Beam(0.22f, 0.03f, 0.022f, 6), p.Dark, new Vector3(0f, 0.155f, 0.22f), Quaternion.Euler(64f, 0f, 0f), Vector3.one);
            wheels.Add(Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.0225f, -0.03f), new Vector2(0.0645f, -0.03f), new Vector2(0.075f, -0.018f), new Vector2(0.075f, 0.018f), new Vector2(0.0645f, 0.03f), new Vector2(0.0225f, 0.03f) }, 22), p.Dark, new Vector3(0f, 0.075f, 0.34f), Quaternion.Euler(0f, 0f, 90f), Vector3.one));
            wheels.Add(Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.039f, -0.0108f), new Vector2(0.045f, 0f), new Vector2(0.039f, 0.0108f) }, 16), p.Dark, new Vector3(0f, 0.075f, 0.34f), Quaternion.Euler(0f, 0f, 90f), Vector3.one));
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.1f, 0f), new Vector2(0.24f, 0.05f), new Vector2(0.3f, 0.16f), new Vector2(0.2971f, 0.2f) }, 28), p.Cool, new Vector3(0f, 0.36f, 0f), Quaternion.identity, Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.2971f, 0.2f), new Vector2(0.29f, 0.3f), new Vector2(0.21f, 0.4f), new Vector2(0.1f, 0.44f) }, 28), p.Warm, new Vector3(0f, 0.36f, 0f), Quaternion.identity, Vector3.one);
            Add(root, CharacterMeshes.Prism(7, 0.2f, 0.15f, 0.26f, 0.3f, 0f), p.Warm, new Vector3(0f, 0.94f, 0.1f), Quaternion.Euler(34f, 0f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.155f, 0f), new Vector2(0.175f, 0.03f), new Vector2(0.13f, 0.075f) }, 10), p.Dark, new Vector3(0f, 1.03f, -0.03f), Quaternion.Euler(34f, 0f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.1008f, 0f), new Vector2(0.1544f, 0.0158f), new Vector2(0.1625f, 0.0325f), new Vector2(0.1463f, 0.0525f) }, 24), p.Dark, new Vector3(0.03f, 0.93f, 0.24f), Quaternion.Euler(50f, 0f, 0f), Vector3.one);
            eyes.Add(Lens(root, CharacterMeshes.Sphere(20), new Vector3(0.03f, 0.9461f, 0.2592f), Quaternion.Euler(-40f, 0f, 0f), new Vector3(0.1938f, 0.1938f, 0.0625f)));
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.042f, 0f), new Vector2(0.055f, 0.012f), new Vector2(0.036f, 0.03f) }, 12), p.Gold, new Vector3(-0.13f, 0.96f, 0.2f), Quaternion.Euler(50f, 0f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Beam(0.22f, 0.016f, 0.007f, 5), p.Dark, new Vector3(0.1f, 1.11f, -0.1f), Quaternion.Euler(8f, 0f, -16f), Vector3.one);
            Add(root, CharacterMeshes.Sphere(10), p.Gold, new Vector3(0.1606f, 1.22f, -0.0694f), Quaternion.identity, new Vector3(0.03f, 0.03f, 0.03f));
            Add(root, CharacterMeshes.Beam(0.15f, 0.016f, 0.007f, 5), p.Dark, new Vector3(-0.07f, 1.075f, -0.13f), Quaternion.Euler(-5f, 0f, 12f), Vector3.one);
        }

        /// <summary>Launcher — formerly "Bomber". A six-cell launcher block on a two-wheel chassis, missile noses visible in the cells. Wheels outboard so it is wide at the bottom and the block reads as payload.</summary>
        private static void BuildLauncher(Transform root, in RobotPalette p,
                                    List<MeshRenderer> eyes, List<Transform> wheels)
        {
            wheels.Add(Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.06f, -0.0575f), new Vector2(0.172f, -0.0575f), new Vector2(0.2f, -0.0345f), new Vector2(0.2f, 0.0345f), new Vector2(0.172f, 0.0575f), new Vector2(0.06f, 0.0575f) }, 22), p.Dark, new Vector3(-0.3f, 0.2f, 0.02f), Quaternion.Euler(0f, 0f, 90f), Vector3.one));
            wheels.Add(Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.104f, -0.0207f), new Vector2(0.12f, 0f), new Vector2(0.104f, 0.0207f) }, 16), p.Warm, new Vector3(-0.3f, 0.2f, 0.02f), Quaternion.Euler(0f, 0f, 90f), Vector3.one));
            wheels.Add(Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.06f, -0.0575f), new Vector2(0.172f, -0.0575f), new Vector2(0.2f, -0.0345f), new Vector2(0.2f, 0.0345f), new Vector2(0.172f, 0.0575f), new Vector2(0.06f, 0.0575f) }, 22), p.Dark, new Vector3(0.3f, 0.2f, 0.02f), Quaternion.Euler(0f, 0f, 90f), Vector3.one));
            wheels.Add(Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.104f, -0.0207f), new Vector2(0.12f, 0f), new Vector2(0.104f, 0.0207f) }, 16), p.Warm, new Vector3(0.3f, 0.2f, 0.02f), Quaternion.Euler(0f, 0f, 90f), Vector3.one));
            Add(root, CharacterMeshes.Beam(0.6f, 0.045f, 0.045f, 6), p.Dark, new Vector3(0f, 0.2f, 0.02f), Quaternion.Euler(0f, 0f, 90f), Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.12f, 0f), new Vector2(0.26f, 0.05f), new Vector2(0.3f, 0.15f), new Vector2(0.2918f, 0.18f) }, 28), p.Cool, new Vector3(0f, 0.32f, 0f), Quaternion.identity, Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.2918f, 0.18f), new Vector2(0.27f, 0.26f), new Vector2(0.14f, 0.32f) }, 28), p.Warm, new Vector3(0f, 0.32f, 0f), Quaternion.identity, Vector3.one);
            Add(root, CharacterMeshes.Prism(6, 0.3f, 0.27f, 0.38f, 0.2f, 0f), p.Warm, new Vector3(0f, 0.96f, -0.05f), Quaternion.Euler(-16f, 90f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Prism(6, 0.31f, 0.31f, 0.05f, 0.3f, 0f), p.Dark, new Vector3(0f, 1.12f, 0.08f), Quaternion.Euler(-16f, 90f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.055f, 0f), new Vector2(0.058f, 0.03f), new Vector2(0.05f, 0.055f) }, 10), p.Dark, new Vector3(-0.15f, 0.9534f, 0.1808f), Quaternion.Euler(74f, 0f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0f, 0f), new Vector2(0.034f, 0.02f), new Vector2(0.041f, 0.05f), new Vector2(0f, 0.12f) }, 10), p.Gold, new Vector3(-0.15f, 0.9684f, 0.2308f), Quaternion.Euler(74f, 0f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.055f, 0f), new Vector2(0.058f, 0.03f), new Vector2(0.05f, 0.055f) }, 10), p.Dark, new Vector3(0f, 0.9534f, 0.1808f), Quaternion.Euler(74f, 0f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0f, 0f), new Vector2(0.034f, 0.02f), new Vector2(0.041f, 0.05f), new Vector2(0f, 0.12f) }, 10), p.Gold, new Vector3(0f, 0.9684f, 0.2308f), Quaternion.Euler(74f, 0f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.055f, 0f), new Vector2(0.058f, 0.03f), new Vector2(0.05f, 0.055f) }, 10), p.Dark, new Vector3(0.15f, 0.9534f, 0.1808f), Quaternion.Euler(74f, 0f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0f, 0f), new Vector2(0.034f, 0.02f), new Vector2(0.041f, 0.05f), new Vector2(0f, 0.12f) }, 10), p.Gold, new Vector3(0.15f, 0.9684f, 0.2308f), Quaternion.Euler(74f, 0f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.055f, 0f), new Vector2(0.058f, 0.03f), new Vector2(0.05f, 0.055f) }, 10), p.Dark, new Vector3(-0.15f, 1.0975f, 0.1394f), Quaternion.Euler(74f, 0f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0f, 0f), new Vector2(0.034f, 0.02f), new Vector2(0.041f, 0.05f), new Vector2(0f, 0.12f) }, 10), p.Gold, new Vector3(-0.15f, 1.1125f, 0.1894f), Quaternion.Euler(74f, 0f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.055f, 0f), new Vector2(0.058f, 0.03f), new Vector2(0.05f, 0.055f) }, 10), p.Dark, new Vector3(0f, 1.0975f, 0.1394f), Quaternion.Euler(74f, 0f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0f, 0f), new Vector2(0.034f, 0.02f), new Vector2(0.041f, 0.05f), new Vector2(0f, 0.12f) }, 10), p.Gold, new Vector3(0f, 1.1125f, 0.1894f), Quaternion.Euler(74f, 0f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.055f, 0f), new Vector2(0.058f, 0.03f), new Vector2(0.05f, 0.055f) }, 10), p.Dark, new Vector3(0.15f, 1.0975f, 0.1394f), Quaternion.Euler(74f, 0f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0f, 0f), new Vector2(0.034f, 0.02f), new Vector2(0.041f, 0.05f), new Vector2(0f, 0.12f) }, 10), p.Gold, new Vector3(0.15f, 1.1125f, 0.1894f), Quaternion.Euler(74f, 0f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Prism(7, 0.14f, 0.17f, 0.2f, 0.24f, 0f), p.Cool, new Vector3(0f, 0.62f, 0.2f), Quaternion.Euler(26f, 0f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.0806f, 0f), new Vector2(0.1235f, 0.0126f), new Vector2(0.13f, 0.026f), new Vector2(0.117f, 0.042f) }, 24), p.Dark, new Vector3(0f, 0.62f, 0.31f), Quaternion.Euler(46f, 0f, 0f), Vector3.one);
            eyes.Add(Lens(root, CharacterMeshes.Sphere(20), new Vector3(0f, 0.6339f, 0.3244f), Quaternion.Euler(-44f, 0f, 0f), new Vector3(0.155f, 0.155f, 0.05f)));
            Add(root, CharacterMeshes.Beam(0.2f, 0.016f, 0.007f, 5), p.Dark, new Vector3(-0.17f, 1.28f, 0.1f), Quaternion.Euler(-9f, 0f, 14f), Vector3.one);
            Add(root, CharacterMeshes.Beam(0.14f, 0.016f, 0.007f, 5), p.Dark, new Vector3(0.18f, 1.23f, 0.08f), Quaternion.Euler(0f, 0f, -9f), Vector3.one);
            Add(root, CharacterMeshes.Sphere(10), p.Gold, new Vector3(0.2019f, 1.3f, 0.08f), Quaternion.identity, new Vector3(0.028f, 0.028f, 0.028f));
        }

        /// <summary>Blinker — one of only two kinds that keeps legs, and it earns them: it teleports rather than closing on foot, so it never needs a walk cycle. A faceted crystal core crouched on tight crossed legs.</summary>
        private static void BuildBlinker(Transform root, in RobotPalette p,
                                    List<MeshRenderer> eyes, List<Transform> wheels)
        {
            Add(root, CharacterMeshes.Beam(0.1541f, 0.03f, 0.024f, 7), p.Dark, new Vector3(-0.0575f, 0.228f, 0f), Quaternion.Euler(0f, 0f, 20.9041f), Vector3.one);
            Add(root, CharacterMeshes.Sphere(12), p.Dark, new Vector3(-0.03f, 0.156f, 0f), Quaternion.identity, new Vector3(0.069f, 0.069f, 0.069f));
            Add(root, CharacterMeshes.Beam(0.1561f, 0.024f, 0.02f, 7), p.Dark, new Vector3(-0.0318f, 0.078f, 0f), Quaternion.Euler(0f, 0f, 6f), Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.038f, 0f), new Vector2(0.026f, 0.045f), new Vector2(0.01f, 0.075f) }, 8), p.Dark, new Vector3(-0.033f, -0.03f, 0.03f), Quaternion.Euler(10f, 0f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Beam(0.1541f, 0.03f, 0.024f, 7), p.Dark, new Vector3(0.0575f, 0.228f, 0f), Quaternion.Euler(0f, 0f, -20.9041f), Vector3.one);
            Add(root, CharacterMeshes.Sphere(12), p.Dark, new Vector3(0.03f, 0.156f, 0f), Quaternion.identity, new Vector3(0.069f, 0.069f, 0.069f));
            Add(root, CharacterMeshes.Beam(0.1561f, 0.024f, 0.02f, 7), p.Dark, new Vector3(0.0318f, 0.078f, 0f), Quaternion.Euler(0f, 0f, -6f), Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.038f, 0f), new Vector2(0.026f, 0.045f), new Vector2(0.01f, 0.075f) }, 8), p.Dark, new Vector3(0.033f, -0.03f, 0.03f), Quaternion.Euler(10f, 0f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.09f, 0f), new Vector2(0.17f, 0.05f), new Vector2(0.1967f, 0.13f) }, 28), p.Cool, new Vector3(0f, 0.28f, 0f), Quaternion.identity, Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.1967f, 0.13f), new Vector2(0.2f, 0.14f), new Vector2(0.18f, 0.22f), new Vector2(0.1f, 0.28f) }, 28), p.Warm, new Vector3(0f, 0.28f, 0f), Quaternion.identity, Vector3.one);
            Add(root, CharacterMeshes.Prism(6, 0.2f, 0.3f, 0.26f, 0.3f, 22f), p.Cool, new Vector3(0f, 0.72f, 0f), Quaternion.identity, Vector3.one);
            Add(root, CharacterMeshes.Prism(6, 0.3f, 0.13f, 0.3f, 0.34f, -18f), p.Warm, new Vector3(0f, 1f, 0f), Quaternion.identity, Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.21f, 0f), new Vector2(0.235f, 0.03f), new Vector2(0.2f, 0.07f) }, 12), p.Gold, new Vector3(0f, 0.855f, 0f), Quaternion.identity, Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.1f, 0f), new Vector2(0.115f, 0.025f), new Vector2(0.08f, 0.06f) }, 10), p.Dark, new Vector3(0f, 1.16f, -0.01f), Quaternion.identity, Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.1008f, 0f), new Vector2(0.1544f, 0.0158f), new Vector2(0.1625f, 0.0325f), new Vector2(0.1463f, 0.0525f) }, 24), p.Dark, new Vector3(0f, 0.86f, 0.245f), Quaternion.Euler(46f, 0f, 0f), Vector3.one);
            eyes.Add(Lens(root, CharacterMeshes.Sphere(20), new Vector3(0f, 0.8774f, 0.263f), Quaternion.Euler(-44f, 0f, 0f), new Vector3(0.1938f, 0.1938f, 0.0625f)));
            Add(root, CharacterMeshes.Beam(0.22f, 0.016f, 0.007f, 5), p.Dark, new Vector3(-0.09f, 1.25f, 0.02f), Quaternion.Euler(0f, 0f, 18f), Vector3.one);
            Add(root, CharacterMeshes.Sphere(10), p.Gold, new Vector3(-0.158f, 1.36f, 0.02f), Quaternion.identity, new Vector3(0.03f, 0.03f, 0.03f));
            Add(root, CharacterMeshes.Beam(0.14f, 0.016f, 0.007f, 5), p.Dark, new Vector3(0.1f, 1.19f, -0.05f), Quaternion.Euler(8f, 0f, -13f), Vector3.one);
        }

        /// <summary>Gunner — the other legged kind, and it earns them the same way — LungeSpeed is 0, it is a planted emplacement. Big head on a thin mast over a tripod.</summary>
        private static void BuildGunner(Transform root, in RobotPalette p,
                                    List<MeshRenderer> eyes, List<Transform> wheels)
        {
            Add(root, CharacterMeshes.Beam(0.34f, 0.036f, 0.022f, 6), p.Dark, new Vector3(0f, 0.17f, 0.165f), Quaternion.Euler(22f, 0f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.055f, 0f), new Vector2(0.038f, 0.03f), new Vector2(0.015f, 0.06f) }, 8), p.Dark, new Vector3(0f, 0.03f, 0.3f), Quaternion.identity, Vector3.one);
            Add(root, CharacterMeshes.Beam(0.34f, 0.036f, 0.022f, 6), p.Dark, new Vector3(0.1429f, 0.17f, -0.0825f), Quaternion.Euler(-11f, 120f, -19.0526f), Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.055f, 0f), new Vector2(0.038f, 0.03f), new Vector2(0.015f, 0.06f) }, 8), p.Dark, new Vector3(0.2598f, 0.03f, -0.15f), Quaternion.identity, Vector3.one);
            Add(root, CharacterMeshes.Beam(0.34f, 0.036f, 0.022f, 6), p.Dark, new Vector3(-0.1429f, 0.17f, -0.0825f), Quaternion.Euler(-11f, 240f, 19.0526f), Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.055f, 0f), new Vector2(0.038f, 0.03f), new Vector2(0.015f, 0.06f) }, 8), p.Dark, new Vector3(-0.2598f, 0.03f, -0.15f), Quaternion.identity, Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.16f, 0f), new Vector2(0.27f, 0.05f), new Vector2(0.285f, 0.11f) }, 28), p.Cool, new Vector3(0f, 0.34f, 0f), Quaternion.identity, Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.285f, 0.11f), new Vector2(0.29f, 0.13f), new Vector2(0.24f, 0.2f), new Vector2(0.12f, 0.24f) }, 28), p.Warm, new Vector3(0f, 0.34f, 0f), Quaternion.identity, Vector3.one);
            Add(root, CharacterMeshes.Beam(0.26f, 0.042f, 0.055f, 7), p.Dark, new Vector3(0f, 0.7f, 0f), Quaternion.identity, Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.075f, 0f), new Vector2(0.088f, 0.012f), new Vector2(0.075f, 0.026f) }, 14), p.Cool, new Vector3(0f, 0.62f, 0f), Quaternion.identity, Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.075f, 0f), new Vector2(0.088f, 0.012f), new Vector2(0.075f, 0.026f) }, 14), p.Cool, new Vector3(0f, 0.7f, 0f), Quaternion.identity, Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.075f, 0f), new Vector2(0.088f, 0.012f), new Vector2(0.075f, 0.026f) }, 14), p.Cool, new Vector3(0f, 0.78f, 0f), Quaternion.identity, Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.1f, 0f), new Vector2(0.34f, 0.06f), new Vector2(0.38f, 0.14f), new Vector2(0.33f, 0.21f), new Vector2(0.14f, 0.25f) }, 22), p.Warm, new Vector3(0f, 0.86f, 0.01f), Quaternion.identity, Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.28f, 0f), new Vector2(0.3f, 0.025f), new Vector2(0.26f, 0.055f) }, 22), p.Cool, new Vector3(0f, 1.11f, 0.01f), Quaternion.identity, Vector3.one);
            Add(root, CharacterMeshes.Beam(0.13f, 0.026f, 0.016f, 5), p.Dark, new Vector3(0.2949f, 0.98f, 0.2065f), Quaternion.Euler(96f, 55f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Beam(0.13f, 0.026f, 0.016f, 5), p.Dark, new Vector3(0.0314f, 0.98f, -0.3586f), Quaternion.Euler(96f, 175f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Beam(0.13f, 0.026f, 0.016f, 5), p.Dark, new Vector3(-0.3263f, 0.98f, 0.1521f), Quaternion.Euler(96f, 295f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.1249f, 0f), new Vector2(0.1914f, 0.0195f), new Vector2(0.2015f, 0.0404f), new Vector2(0.1814f, 0.0651f) }, 24), p.Dark, new Vector3(0f, 0.99f, 0.31f), Quaternion.Euler(44f, 0f, 0f), Vector3.one);
            eyes.Add(Lens(root, CharacterMeshes.Sphere(20), new Vector3(0f, 1.0123f, 0.3315f), Quaternion.Euler(-46f, 0f, 0f), new Vector3(0.2402f, 0.2402f, 0.0775f)));
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.09f, 0f), new Vector2(0.1f, 0.012f), new Vector2(0.085f, 0.026f) }, 16), p.Gold, new Vector3(0f, 1.15f, 0.01f), Quaternion.identity, Vector3.one);
            Add(root, CharacterMeshes.Beam(0.24f, 0.016f, 0.007f, 5), p.Dark, new Vector3(0.13f, 1.26f, -0.09f), Quaternion.Euler(6f, 0f, -20f), Vector3.one);
            Add(root, CharacterMeshes.Sphere(10), p.Gold, new Vector3(0.2121f, 1.38f, -0.0649f), Quaternion.identity, new Vector3(0.03f, 0.03f, 0.03f));
            Add(root, CharacterMeshes.Beam(0.15f, 0.016f, 0.007f, 5), p.Dark, new Vector3(-0.1f, 1.195f, -0.11f), Quaternion.Euler(0f, 0f, 15f), Vector3.one);
        }

        /// <summary>Bruiser — two long tread units under a low wide hull, with the garden-roller drum slung across the front. Keeps its two-eye visor: one kind breaking the one-eye rule is what makes the rule legible.</summary>
        private static void BuildBruiser(Transform root, in RobotPalette p,
                                    List<MeshRenderer> eyes, List<Transform> wheels)
        {
            Add(root, CharacterMeshes.Prism(4, 0.155f, 0.155f, 0.72f, 0.02f, 0f), p.Dark, new Vector3(-0.4f, 0.155f, 0f), Quaternion.Euler(0f, 0f, 90f), new Vector3(1f, 0.6129f, 1f));
            wheels.Add(Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.0465f, -0.095f), new Vector2(0.1426f, -0.095f), new Vector2(0.155f, -0.0532f), new Vector2(0.155f, 0.0532f), new Vector2(0.1426f, 0.095f), new Vector2(0.0465f, 0.095f) }, 18), p.Dark, new Vector3(-0.4f, 0.155f, -0.36f), Quaternion.Euler(0f, 0f, 90f), Vector3.one));
            wheels.Add(Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.062f, -0.0304f), new Vector2(0.0713f, 0f), new Vector2(0.062f, 0.0304f) }, 12), p.Warm, new Vector3(-0.4f, 0.155f, -0.36f), Quaternion.Euler(0f, 0f, 90f), Vector3.one));
            wheels.Add(Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.0465f, -0.095f), new Vector2(0.1426f, -0.095f), new Vector2(0.155f, -0.0532f), new Vector2(0.155f, 0.0532f), new Vector2(0.1426f, 0.095f), new Vector2(0.0465f, 0.095f) }, 18), p.Dark, new Vector3(-0.4f, 0.155f, 0.36f), Quaternion.Euler(0f, 0f, 90f), Vector3.one));
            wheels.Add(Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.062f, -0.0304f), new Vector2(0.0713f, 0f), new Vector2(0.062f, 0.0304f) }, 12), p.Warm, new Vector3(-0.4f, 0.155f, 0.36f), Quaternion.Euler(0f, 0f, 90f), Vector3.one));
            wheels.Add(Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.0682f, -0.057f), new Vector2(0.0775f, 0f), new Vector2(0.0682f, 0.057f) }, 12), p.Dark, new Vector3(-0.4f, 0.1085f, -0.2016f), Quaternion.Euler(0f, 0f, 90f), Vector3.one));
            wheels.Add(Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.0682f, -0.057f), new Vector2(0.0775f, 0f), new Vector2(0.0682f, 0.057f) }, 12), p.Dark, new Vector3(-0.4f, 0.1085f, 0.2016f), Quaternion.Euler(0f, 0f, 90f), Vector3.one));
            Add(root, CharacterMeshes.Prism(4, 0.155f, 0.155f, 0.72f, 0.02f, 0f), p.Dark, new Vector3(0.4f, 0.155f, 0f), Quaternion.Euler(0f, 0f, 90f), new Vector3(1f, 0.6129f, 1f));
            wheels.Add(Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.0465f, -0.095f), new Vector2(0.1426f, -0.095f), new Vector2(0.155f, -0.0532f), new Vector2(0.155f, 0.0532f), new Vector2(0.1426f, 0.095f), new Vector2(0.0465f, 0.095f) }, 18), p.Dark, new Vector3(0.4f, 0.155f, -0.36f), Quaternion.Euler(0f, 0f, 90f), Vector3.one));
            wheels.Add(Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.062f, -0.0304f), new Vector2(0.0713f, 0f), new Vector2(0.062f, 0.0304f) }, 12), p.Warm, new Vector3(0.4f, 0.155f, -0.36f), Quaternion.Euler(0f, 0f, 90f), Vector3.one));
            wheels.Add(Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.0465f, -0.095f), new Vector2(0.1426f, -0.095f), new Vector2(0.155f, -0.0532f), new Vector2(0.155f, 0.0532f), new Vector2(0.1426f, 0.095f), new Vector2(0.0465f, 0.095f) }, 18), p.Dark, new Vector3(0.4f, 0.155f, 0.36f), Quaternion.Euler(0f, 0f, 90f), Vector3.one));
            wheels.Add(Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.062f, -0.0304f), new Vector2(0.0713f, 0f), new Vector2(0.062f, 0.0304f) }, 12), p.Warm, new Vector3(0.4f, 0.155f, 0.36f), Quaternion.Euler(0f, 0f, 90f), Vector3.one));
            wheels.Add(Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.0682f, -0.057f), new Vector2(0.0775f, 0f), new Vector2(0.0682f, 0.057f) }, 12), p.Dark, new Vector3(0.4f, 0.1085f, -0.2016f), Quaternion.Euler(0f, 0f, 90f), Vector3.one));
            wheels.Add(Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.0682f, -0.057f), new Vector2(0.0775f, 0f), new Vector2(0.0682f, 0.057f) }, 12), p.Dark, new Vector3(0.4f, 0.1085f, 0.2016f), Quaternion.Euler(0f, 0f, 90f), Vector3.one));
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.34f, 0f), new Vector2(0.5f, 0.05f), new Vector2(0.53f, 0.16f), new Vector2(0.5167f, 0.2f) }, 28), p.Cool, new Vector3(0f, 0.3f, 0f), Quaternion.identity, Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.5167f, 0.2f), new Vector2(0.49f, 0.28f), new Vector2(0.34f, 0.36f), new Vector2(0.16f, 0.4f) }, 28), p.Warm, new Vector3(0f, 0.3f, 0f), Quaternion.identity, Vector3.one);
            Add(root, CharacterMeshes.Prism(7, 0.35f, 0.3f, 0.2f, 0.28f, 0f), p.Warm, new Vector3(0f, 0.78f, 0.1f), Quaternion.Euler(14f, 0f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.079f, 0f), new Vector2(0.121f, 0.0123f), new Vector2(0.1274f, 0.0255f), new Vector2(0.1147f, 0.0412f) }, 24), p.Dark, new Vector3(-0.145f, 0.77f, 0.3f), Quaternion.Euler(50f, 0f, 0f), Vector3.one);
            eyes.Add(Lens(root, CharacterMeshes.Sphere(20), new Vector3(-0.145f, 0.7826f, 0.315f), Quaternion.Euler(-40f, 0f, 0f), new Vector3(0.1519f, 0.1519f, 0.049f)));
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.079f, 0f), new Vector2(0.121f, 0.0123f), new Vector2(0.1274f, 0.0255f), new Vector2(0.1147f, 0.0412f) }, 24), p.Dark, new Vector3(0.145f, 0.77f, 0.3f), Quaternion.Euler(50f, 0f, 0f), Vector3.one);
            eyes.Add(Lens(root, CharacterMeshes.Sphere(20), new Vector3(0.145f, 0.7826f, 0.315f), Quaternion.Euler(-40f, 0f, 0f), new Vector3(0.1519f, 0.1519f, 0.049f)));
            wheels.Add(Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.19f, 0f), new Vector2(0.215f, 0.06f), new Vector2(0.215f, 0.3f), new Vector2(0.19f, 0.36f) }, 20), p.Cool, new Vector3(-0.18f, 0.185f, 0.5f), Quaternion.Euler(0f, 0f, 90f), Vector3.one));
            wheels.Add(Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.13f, 0f), new Vector2(0.15f, 0.02f), new Vector2(0.125f, 0.045f) }, 16), p.Gold, new Vector3(-0.205f, 0.185f, 0.5f), Quaternion.Euler(0f, 0f, 90f), Vector3.one));
            Add(root, CharacterMeshes.Prism(6, 0.085f, 0.07f, 0.28f, 0.24f, 0f), p.Dark, new Vector3(-0.4f, 0.56f, 0.24f), Quaternion.Euler(78f, 10f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Prism(6, 0.085f, 0.07f, 0.28f, 0.24f, 0f), p.Dark, new Vector3(0.4f, 0.56f, 0.24f), Quaternion.Euler(78f, -10f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Beam(0.2f, 0.016f, 0.007f, 5), p.Dark, new Vector3(0.24f, 0.96f, -0.22f), Quaternion.Euler(8f, 0f, -14f), Vector3.one);
            Add(root, CharacterMeshes.Sphere(10), p.Gold, new Vector3(0.2884f, 1.06f, -0.1922f), Quaternion.identity, new Vector3(0.03f, 0.03f, 0.03f));
            Add(root, CharacterMeshes.Beam(0.13f, 0.016f, 0.007f, 5), p.Dark, new Vector3(-0.18f, 0.925f, -0.26f), Quaternion.Euler(0f, 0f, 11f), Vector3.one);
        }

        /// <summary>Heavy — a barrel riding one huge garden-roller drum with trailing castors. The roller is the garden motif AND the thing that turns. Had no body of its own before this.</summary>
        private static void BuildHeavy(Transform root, in RobotPalette p,
                                    List<MeshRenderer> eyes, List<Transform> wheels)
        {
            wheels.Add(Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.1f, -0.24f), new Vector2(0.3f, -0.24f), new Vector2(0.325f, -0.2f), new Vector2(0.325f, 0.2f), new Vector2(0.3f, 0.24f), new Vector2(0.1f, 0.24f) }, 24), p.Cool, new Vector3(0f, 0.325f, -0.02f), Quaternion.Euler(0f, 0f, 90f), Vector3.one));
            wheels.Add(Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.14f, -0.245f), new Vector2(0.16f, -0.225f), new Vector2(0.14f, -0.205f) }, 14), p.Dark, new Vector3(0f, 0.325f, -0.02f), Quaternion.Euler(0f, 0f, 90f), Vector3.one));
            wheels.Add(Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.14f, 0.205f), new Vector2(0.16f, 0.225f), new Vector2(0.14f, 0.245f) }, 14), p.Dark, new Vector3(0f, 0.325f, -0.02f), Quaternion.Euler(0f, 0f, 90f), Vector3.one));
            Add(root, CharacterMeshes.Beam(0.26f, 0.038f, 0.03f, 6), p.Dark, new Vector3(-0.24f, 0.2f, 0.26f), Quaternion.Euler(58f, 0f, 0f), Vector3.one);
            wheels.Add(Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.0225f, -0.031f), new Vector2(0.0645f, -0.031f), new Vector2(0.075f, -0.0186f), new Vector2(0.075f, 0.0186f), new Vector2(0.0645f, 0.031f), new Vector2(0.0225f, 0.031f) }, 22), p.Dark, new Vector3(-0.24f, 0.075f, 0.38f), Quaternion.Euler(0f, 0f, 90f), Vector3.one));
            wheels.Add(Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.039f, -0.0112f), new Vector2(0.045f, 0f), new Vector2(0.039f, 0.0112f) }, 16), p.Dark, new Vector3(-0.24f, 0.075f, 0.38f), Quaternion.Euler(0f, 0f, 90f), Vector3.one));
            Add(root, CharacterMeshes.Beam(0.26f, 0.038f, 0.03f, 6), p.Dark, new Vector3(0.24f, 0.2f, 0.26f), Quaternion.Euler(58f, 0f, 0f), Vector3.one);
            wheels.Add(Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.0225f, -0.031f), new Vector2(0.0645f, -0.031f), new Vector2(0.075f, -0.0186f), new Vector2(0.075f, 0.0186f), new Vector2(0.0645f, 0.031f), new Vector2(0.0225f, 0.031f) }, 22), p.Dark, new Vector3(0.24f, 0.075f, 0.38f), Quaternion.Euler(0f, 0f, 90f), Vector3.one));
            wheels.Add(Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.039f, -0.0112f), new Vector2(0.045f, 0f), new Vector2(0.039f, 0.0112f) }, 16), p.Dark, new Vector3(0.24f, 0.075f, 0.38f), Quaternion.Euler(0f, 0f, 90f), Vector3.one));
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.22f, 0f), new Vector2(0.38f, 0.09f), new Vector2(0.43f, 0.32f), new Vector2(0.4277f, 0.38f) }, 28), p.Cool, new Vector3(0f, 0.56f, 0f), Quaternion.identity, Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.4277f, 0.38f), new Vector2(0.42f, 0.58f), new Vector2(0.32f, 0.74f), new Vector2(0.16f, 0.82f) }, 28), p.Warm, new Vector3(0f, 0.56f, 0f), Quaternion.identity, Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.45f, 0f), new Vector2(0.475f, 0.022f), new Vector2(0.45f, 0.044f) }, 24), p.Dark, new Vector3(0f, 0.94f, -0.02f), Quaternion.identity, Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.42f, 0f), new Vector2(0.445f, 0.022f), new Vector2(0.42f, 0.044f) }, 24), p.Dark, new Vector3(0f, 1.24f, -0.02f), Quaternion.identity, Vector3.one);
            Add(root, CharacterMeshes.Beam(0.1f, 0.11f, 0.13f, 8), p.Dark, new Vector3(0f, 1.52f, -0.02f), Quaternion.identity, Vector3.one);
            Add(root, CharacterMeshes.Prism(7, 0.25f, 0.22f, 0.24f, 0.24f, 0f), p.Cool, new Vector3(0f, 1.66f, 0.01f), Quaternion.Euler(12f, 0f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.1008f, 0f), new Vector2(0.1544f, 0.0158f), new Vector2(0.1625f, 0.0325f), new Vector2(0.1463f, 0.0525f) }, 24), p.Dark, new Vector3(0.03f, 1.65f, 0.18f), Quaternion.Euler(48f, 0f, 0f), Vector3.one);
            eyes.Add(Lens(root, CharacterMeshes.Sphere(20), new Vector3(0.03f, 1.6667f, 0.1986f), Quaternion.Euler(-42f, 0f, 0f), new Vector3(0.25f, 0.0775f, 0.0625f)));
            Add(root, CharacterMeshes.Beam(0.2f, 0.016f, 0.007f, 5), p.Dark, new Vector3(0.19f, 1.88f, -0.1f), Quaternion.Euler(7f, 0f, -12f), Vector3.one);
            Add(root, CharacterMeshes.Sphere(10), p.Gold, new Vector3(0.2316f, 1.98f, -0.0756f), Quaternion.identity, new Vector3(0.034f, 0.034f, 0.034f));
            Add(root, CharacterMeshes.Beam(0.14f, 0.016f, 0.007f, 5), p.Dark, new Vector3(-0.14f, 1.85f, -0.14f), Quaternion.Euler(-6f, 0f, 9f), Vector3.one);
        }

        /// <summary>Brute — a wall on four heavy road wheels. Nothing else in the roster has four, so it is identifiable by its undercarriage alone at twenty pixels. Also had no body of its own before this.</summary>
        private static void BuildBrute(Transform root, in RobotPalette p,
                                    List<MeshRenderer> eyes, List<Transform> wheels)
        {
            wheels.Add(Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.0645f, -0.0725f), new Vector2(0.1849f, -0.0725f), new Vector2(0.215f, -0.0435f), new Vector2(0.215f, 0.0435f), new Vector2(0.1849f, 0.0725f), new Vector2(0.0645f, 0.0725f) }, 22), p.Dark, new Vector3(-0.4f, 0.215f, -0.3f), Quaternion.Euler(0f, 0f, 90f), Vector3.one));
            wheels.Add(Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.1118f, -0.0261f), new Vector2(0.129f, 0f), new Vector2(0.1118f, 0.0261f) }, 16), p.Warm, new Vector3(-0.4f, 0.215f, -0.3f), Quaternion.Euler(0f, 0f, 90f), Vector3.one));
            wheels.Add(Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.0645f, -0.0725f), new Vector2(0.1849f, -0.0725f), new Vector2(0.215f, -0.0435f), new Vector2(0.215f, 0.0435f), new Vector2(0.1849f, 0.0725f), new Vector2(0.0645f, 0.0725f) }, 22), p.Dark, new Vector3(-0.4f, 0.215f, 0.3f), Quaternion.Euler(0f, 0f, 90f), Vector3.one));
            wheels.Add(Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.1118f, -0.0261f), new Vector2(0.129f, 0f), new Vector2(0.1118f, 0.0261f) }, 16), p.Warm, new Vector3(-0.4f, 0.215f, 0.3f), Quaternion.Euler(0f, 0f, 90f), Vector3.one));
            wheels.Add(Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.0645f, -0.0725f), new Vector2(0.1849f, -0.0725f), new Vector2(0.215f, -0.0435f), new Vector2(0.215f, 0.0435f), new Vector2(0.1849f, 0.0725f), new Vector2(0.0645f, 0.0725f) }, 22), p.Dark, new Vector3(0.4f, 0.215f, -0.3f), Quaternion.Euler(0f, 0f, 90f), Vector3.one));
            wheels.Add(Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.1118f, -0.0261f), new Vector2(0.129f, 0f), new Vector2(0.1118f, 0.0261f) }, 16), p.Warm, new Vector3(0.4f, 0.215f, -0.3f), Quaternion.Euler(0f, 0f, 90f), Vector3.one));
            wheels.Add(Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.0645f, -0.0725f), new Vector2(0.1849f, -0.0725f), new Vector2(0.215f, -0.0435f), new Vector2(0.215f, 0.0435f), new Vector2(0.1849f, 0.0725f), new Vector2(0.0645f, 0.0725f) }, 22), p.Dark, new Vector3(0.4f, 0.215f, 0.3f), Quaternion.Euler(0f, 0f, 90f), Vector3.one));
            wheels.Add(Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.1118f, -0.0261f), new Vector2(0.129f, 0f), new Vector2(0.1118f, 0.0261f) }, 16), p.Warm, new Vector3(0.4f, 0.215f, 0.3f), Quaternion.Euler(0f, 0f, 90f), Vector3.one));
            Add(root, CharacterMeshes.Beam(0.6f, 0.05f, 0.05f, 6), p.Dark, new Vector3(-0.4f, 0.215f, 0f), Quaternion.Euler(90f, 0f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Beam(0.6f, 0.05f, 0.05f, 6), p.Dark, new Vector3(0.4f, 0.215f, 0f), Quaternion.Euler(90f, 0f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Prism(6, 0.42f, 0.38f, 0.16f, 0.2f, 0f), p.Dark, new Vector3(0f, 0.34f, 0f), Quaternion.identity, Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.3f, 0f), new Vector2(0.46f, 0.07f), new Vector2(0.52f, 0.24f), new Vector2(0.5145f, 0.3f) }, 28), p.Cool, new Vector3(0f, 0.44f, 0f), Quaternion.identity, Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.5145f, 0.3f), new Vector2(0.5f, 0.46f), new Vector2(0.4f, 0.6f), new Vector2(0.22f, 0.66f) }, 28), p.Warm, new Vector3(0f, 0.44f, 0f), Quaternion.identity, Vector3.one);
            Add(root, CharacterMeshes.Prism(8, 0.5f, 0.42f, 0.32f, 0.26f, 0f), p.Warm, new Vector3(0f, 1.2f, -0.01f), Quaternion.identity, Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.42f, 0f), new Vector2(0.45f, 0.035f), new Vector2(0.38f, 0.08f) }, 8), p.Dark, new Vector3(0f, 1.37f, -0.01f), Quaternion.identity, Vector3.one);
            Add(root, CharacterMeshes.Prism(6, 0.21f, 0.17f, 0.2f, 0.28f, 0f), p.Cool, new Vector3(0f, 1.56f, 0.08f), Quaternion.Euler(18f, 0f, 0f), Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.0685f, 0f), new Vector2(0.105f, 0.0107f), new Vector2(0.1105f, 0.0221f), new Vector2(0.0995f, 0.0357f) }, 24), p.Dark, new Vector3(-0.06f, 1.55f, 0.24f), Quaternion.Euler(46f, 0f, 0f), Vector3.one);
            eyes.Add(Lens(root, CharacterMeshes.Sphere(20), new Vector3(-0.06f, 1.5618f, 0.2522f), Quaternion.Euler(-44f, 0f, 0f), new Vector3(0.1318f, 0.1318f, 0.0425f)));
            Add(root, CharacterMeshes.Beam(0.3f, 0.1f, 0.075f, 7), p.Dark, new Vector3(-0.54f, 1.1f, 0.03f), Quaternion.Euler(0f, 0f, 84f), Vector3.one);
            Add(root, CharacterMeshes.Prism(7, 0.16f, 0.2f, 0.32f, 0.24f, 0f), p.Warm, new Vector3(-0.68f, 0.8f, 0.05f), Quaternion.Euler(0f, 0f, -7f), Vector3.one);
            Add(root, CharacterMeshes.Lathe(new[] { new Vector2(0.1f, 0f), new Vector2(0.13f, 0.04f), new Vector2(0.09f, 0.09f) }, 7), p.Dark, new Vector3(0.54f, 1.12f, 0.02f), Quaternion.Euler(0f, 0f, 90f), Vector3.one);
            Add(root, CharacterMeshes.Beam(0.22f, 0.016f, 0.007f, 5), p.Dark, new Vector3(0.28f, 1.59f, -0.14f), Quaternion.Euler(8f, 0f, -13f), Vector3.one);
            Add(root, CharacterMeshes.Sphere(10), p.Gold, new Vector3(0.3295f, 1.7f, -0.1094f), Quaternion.identity, new Vector3(0.032f, 0.032f, 0.032f));
            Add(root, CharacterMeshes.Beam(0.15f, 0.016f, 0.007f, 5), p.Dark, new Vector3(-0.22f, 1.555f, -0.18f), Quaternion.Euler(-6f, 0f, 11f), Vector3.one);
        }

        // ------------------------------------------------------------------ plumbing

        private static Transform Add(Transform root, Mesh mesh, Material mat,
                                     Vector3 at, Quaternion rot, Vector3 scale)
            => CharacterPart.Add(root, mesh, mat, at, rot, scale);

        private static MeshRenderer Lens(Transform root, Mesh mesh,
                                         Vector3 at, Quaternion rot, Vector3 scale)
            => CharacterPart.AddLens(root, mesh, at, rot, scale);
    }
}
