using System.Collections.Generic;
using UnityEngine;

namespace MaxWorlds.Audio
{
    /// <summary>The four waveforms an sfxr-style preset can pick (MV-1007). Noise ignores
    /// <see cref="SfxPreset.BaseFreq"/>/<see cref="SfxPreset.FreqSlide"/>/vibrato entirely — it has no
    /// pitch — and reads <see cref="SfxPreset.Seed"/> instead, so the same preset always renders the
    /// same buffer.</summary>
    public enum SfxWaveform { Sine, Square, Saw, Noise }

    /// <summary>One synthesised tone (MV-1007): waveform, base freq, freq slide, vibrato,
    /// attack/sustain/decay, low-pass cutoff, duty and volume — exactly the knob set the ticket
    /// specifies. A cue is one or more of these played back to back; see
    /// <see cref="ProcSfx.Render"/>.</summary>
    public struct SfxPreset
    {
        public SfxWaveform Waveform;
        public float BaseFreq;       // Hz (ignored by Noise)
        public float FreqSlide;      // Hz added per second, +/- (ignored by Noise)
        public float VibratoDepth;   // Hz, 0 = none (ignored by Noise)
        public float VibratoRate;    // Hz (ignored by Noise)
        public float Attack;         // s
        public float Sustain;        // s
        public float Decay;          // s
        public float LowPassCutoff;  // Hz, 0 = no filter
        public float Duty;           // 0..1, Square only (0 defaults to 0.5)
        public float Volume;         // 0..1, relative weight — see Render
        public int Seed;             // Noise determinism
    }

    /// <summary>
    /// sfxr-style procedural synth (MV-1007): every sound effect in the game is generated by this
    /// class from a table of authored knobs (<see cref="SfxCueLibrary"/>) — no audio asset files, no
    /// external tools, nothing originated by Lee. Deterministic (seeded <see cref="System.Random"/>,
    /// no <c>UnityEngine.Random</c>/<c>Time</c> reads) so the same preset always renders the same
    /// samples, and cheap enough — a handful of trig ops per sample, one output-buffer allocation per
    /// note — that <see cref="SfxDirector"/> rendering the whole cue library once at boot stays well
    /// inside the ticket's 150ms budget.
    /// </summary>
    public static class ProcSfx
    {
        public const int SampleRate = 22050;

        // A cue with a tiny authored duration would round to too few samples to read as a sound (and
        // would fail the ticket's own "≥ 2,000 samples" floor) — every note is at least this long.
        private const float MinNoteSeconds = 0.12f;

        // Keeps every rendered cue's peak comfortably inside the ticket's [0.2, 1.0] band regardless
        // of how a preset's own filtering/waveform choices happen to shape its raw amplitude — see
        // NormalizePeak.
        private const float MinTargetPeak = 0.25f;
        private const float MaxTargetPeak = 0.95f;

        /// <summary>
        /// Renders one cue — one or more notes played back to back — to a mono sample buffer at
        /// <see cref="SampleRate"/>. The FIRST note's <see cref="SfxPreset.Volume"/> sets the whole
        /// cue's target peak (clamped into a safe band); every note's own Volume beyond that is only a
        /// RELATIVE weight against its neighbours, so a multi-note sequence's later notes can sit
        /// quieter or louder than its first without fighting the final normalisation pass.
        /// </summary>
        public static float[] Render(params SfxPreset[] notes)
        {
            var raw = new List<float>();
            foreach (var note in notes) raw.AddRange(RenderRawNote(note));
            var buf = raw.ToArray();
            NormalizePeak(buf, notes.Length > 0 ? notes[0].Volume : 0.6f);
            return buf;
        }

        /// <summary>Wraps <see cref="Render"/> into a playable <see cref="AudioClip"/> — the boot-time
        /// render <see cref="SfxDirector"/> does once per cue.</summary>
        public static AudioClip RenderClip(string name, params SfxPreset[] notes)
        {
            float[] samples = Render(notes);
            var clip = AudioClip.Create(name, samples.Length, 1, SampleRate, false);
            clip.SetData(samples, 0);
            return clip;
        }

        private static float[] RenderRawNote(SfxPreset p)
        {
            float duration = Mathf.Max(MinNoteSeconds, p.Attack + p.Sustain + p.Decay);
            int n = Mathf.Max(1, Mathf.RoundToInt(duration * SampleRate));
            var buf = new float[n];
            var rng = new System.Random(p.Seed);
            float phase = 0f;

            for (int i = 0; i < n; i++)
            {
                float t = i / (float)SampleRate;

                float raw;
                if (p.Waveform == SfxWaveform.Noise)
                {
                    raw = (float)(rng.NextDouble() * 2.0 - 1.0);
                }
                else
                {
                    float freq = p.BaseFreq + p.FreqSlide * t;
                    if (p.VibratoDepth > 0f) freq += p.VibratoDepth * Mathf.Sin(2f * Mathf.PI * p.VibratoRate * t);
                    freq = Mathf.Max(20f, freq);

                    phase += freq / SampleRate;
                    phase -= Mathf.Floor(phase);

                    raw = p.Waveform switch
                    {
                        SfxWaveform.Sine => Mathf.Sin(2f * Mathf.PI * phase),
                        SfxWaveform.Square => phase < (p.Duty <= 0f ? 0.5f : Mathf.Clamp01(p.Duty)) ? 1f : -1f,
                        SfxWaveform.Saw => 2f * phase - 1f,
                        _ => 0f,
                    };
                }

                buf[i] = raw * Envelope(t, p.Attack, p.Sustain, p.Decay) * Mathf.Max(0.01f, p.Volume);
            }

            if (p.LowPassCutoff > 0f) ApplyLowPass(buf, p.LowPassCutoff);
            return buf;
        }

        private static float Envelope(float t, float attack, float sustain, float decay)
        {
            if (attack > 0f && t < attack) return t / attack;
            if (t < attack + sustain) return 1f;
            float decayT = t - attack - sustain;
            return decay > 0f ? Mathf.Clamp01(1f - decayT / decay) : 0f;
        }

        /// <summary>A single one-pole low-pass (RC filter) — enough to turn Noise's flat hiss into a
        /// duller "tss"/whoosh/rumble without needing a real DSP library.</summary>
        private static void ApplyLowPass(float[] buf, float cutoffHz)
        {
            float rc = 1f / (2f * Mathf.PI * cutoffHz);
            const float dt = 1f / SampleRate;
            float alpha = dt / (rc + dt);
            float prev = 0f;
            for (int i = 0; i < buf.Length; i++)
            {
                prev += alpha * (buf[i] - prev);
                buf[i] = prev;
            }
        }

        /// <summary>Rescales the whole buffer so its peak sample lands exactly at
        /// <paramref name="targetPeak"/> (clamped into a safe band) — see <see cref="Render"/>. A
        /// truly silent input (a malformed preset) stays silent rather than amplifying noise floor
        /// into something audible.</summary>
        private static void NormalizePeak(float[] buf, float targetPeak)
        {
            float target = Mathf.Clamp(targetPeak, MinTargetPeak, MaxTargetPeak);
            float peak = 0f;
            for (int i = 0; i < buf.Length; i++) peak = Mathf.Max(peak, Mathf.Abs(buf[i]));
            if (peak < 1e-6f) return;
            float scale = target / peak;
            for (int i = 0; i < buf.Length; i++) buf[i] *= scale;
        }
    }
}
